// Command genseed reads catalog.yml and writes migrations/002_seed.sql.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/habitforge/backend/internal/game"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	catalogPath := filepath.Join(root, "configs", "catalog.yml")
	data, err := os.ReadFile(catalogPath)
	if err != nil {
		catalogPath = filepath.Join(root, "internal", "game", "catalog.yml")
		data, err = os.ReadFile(catalogPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read catalog: %v\n", err)
			os.Exit(1)
		}
	}
	cat, err := game.ParseCatalog(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse catalog: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("-- AUTO-GENERATED by cmd/genseed — do not edit by hand.\n")
	b.WriteString("-- Regenerated from catalog.yml\n\n")

	b.WriteString("-- game_constants\n")
	b.WriteString("INSERT INTO game_constants (key, value) VALUES\n")
	constants := [][2]string{
		{"max_level", strconv.Itoa(game.MaxLevel)},
		{"max_hp", strconv.Itoa(game.MaxHp)},
		{"initial_hp", strconv.Itoa(game.InitialHp)},
		{"death_recovery_minutes", strconv.Itoa(game.DeathRecoveryMinutes)},
		{"death_recovery_hp", strconv.Itoa(game.DeathRecoveryHp)},
		{"complete_task_add_hp", strconv.Itoa(game.CompleteTaskAddHp)},
		{"stat_points_per_level", strconv.Itoa(game.StatPointsPerLevel)},
		{"exp_easy", strconv.Itoa(game.ExpEasy)},
		{"exp_medium", strconv.Itoa(game.ExpMedium)},
		{"exp_hard", strconv.Itoa(game.ExpHard)},
		{"gold_easy", strconv.Itoa(game.GoldEasy)},
		{"gold_medium", strconv.Itoa(game.GoldMedium)},
		{"gold_hard", strconv.Itoa(game.GoldHard)},
	}
	for i, kv := range constants {
		sep := ","
		if i == len(constants)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  (%s, %s)%s\n", sqlStr(kv[0]), sqlStr(kv[1]), sep)
	}
	b.WriteString("ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;\n\n")

	b.WriteString("-- achievement_defs\n")
	b.WriteString("INSERT INTO achievement_defs (id, title, description, condition_type, threshold, gem_reward) VALUES\n")
	for i, a := range cat.Achievements {
		sep := ","
		if i == len(cat.Achievements)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  (%s, %s, %s, %s, %d, %d)%s\n",
			sqlStr(a.ID), sqlStr(a.Title), sqlStr(a.Description), sqlStr(a.ConditionType), a.Threshold, a.GemReward, sep)
	}
	b.WriteString("ON CONFLICT (id) DO UPDATE SET\n")
	b.WriteString("  title = EXCLUDED.title,\n")
	b.WriteString("  description = EXCLUDED.description,\n")
	b.WriteString("  condition_type = EXCLUDED.condition_type,\n")
	b.WriteString("  threshold = EXCLUDED.threshold,\n")
	b.WriteString("  gem_reward = EXCLUDED.gem_reward;\n\n")

	b.WriteString("-- shop_items\n")
	b.WriteString("INSERT INTO shop_items (id, name, description, price, slot, rarity, currency, icon, category, stat_str, stat_int, stat_agi, stat_def, stat_vit, stat_luk) VALUES\n")
	for i, it := range cat.Items {
		sep := ","
		if i == len(cat.Items)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  (%s, %s, %s, %d, %s, %s, %s, %s, %s, %d, %d, %d, %d, %d, %d)%s\n",
			sqlStr(it.ID), sqlStr(it.Name), sqlStr(it.Description), it.Price,
			sqlStr(it.Slot), sqlStr(it.Rarity), sqlStr(it.Currency), sqlStr(it.Icon), sqlStr(it.Category),
			it.Stats.Strength, it.Stats.Intelligence, it.Stats.Agility,
			it.Stats.Defense, it.Stats.Vitality, it.Stats.Luck, sep)
	}
	b.WriteString("ON CONFLICT (id) DO UPDATE SET\n")
	b.WriteString("  name = EXCLUDED.name,\n")
	b.WriteString("  description = EXCLUDED.description,\n")
	b.WriteString("  price = EXCLUDED.price,\n")
	b.WriteString("  slot = EXCLUDED.slot,\n")
	b.WriteString("  rarity = EXCLUDED.rarity,\n")
	b.WriteString("  currency = EXCLUDED.currency,\n")
	b.WriteString("  icon = EXCLUDED.icon,\n")
	b.WriteString("  category = EXCLUDED.category,\n")
	b.WriteString("  stat_str = EXCLUDED.stat_str,\n")
	b.WriteString("  stat_int = EXCLUDED.stat_int,\n")
	b.WriteString("  stat_agi = EXCLUDED.stat_agi,\n")
	b.WriteString("  stat_def = EXCLUDED.stat_def,\n")
	b.WriteString("  stat_vit = EXCLUDED.stat_vit,\n")
	b.WriteString("  stat_luk = EXCLUDED.stat_luk;\n")

	outPath := filepath.Join(root, "migrations", "002_seed.sql")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d items, %d achievements)\n", outPath, len(cat.Items), len(cat.Achievements))
}

func sqlStr(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
