// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/task/v1/task.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskType — habit (daily repeat), daily (weekday repeat), todo (due date).
type TaskType int32

const (
	// Unspecified type; used as the zero value.
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	// Habit — repeats every day.
	TaskType_TASK_TYPE_HABIT TaskType = 1
	// Daily — repeats on the selected weekdays.
	TaskType_TASK_TYPE_DAILY TaskType = 2
	// Todo — one-off task with an optional due date.
	TaskType_TASK_TYPE_TODO TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_HABIT",
		2: "TASK_TYPE_DAILY",
		3: "TASK_TYPE_TODO",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_HABIT":       1,
		"TASK_TYPE_DAILY":       2,
		"TASK_TYPE_TODO":        3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_api_task_v1_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{0}
}

// TaskDifficulty — drives base EXP/gold rewards.
type TaskDifficulty int32

const (
	// Unspecified difficulty; used as the zero value.
	TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED TaskDifficulty = 0
	// Easy — lowest base reward (15 EXP / 5 gold).
	TaskDifficulty_TASK_DIFFICULTY_EASY TaskDifficulty = 1
	// Medium — default difficulty (30 EXP / 10 gold).
	TaskDifficulty_TASK_DIFFICULTY_MEDIUM TaskDifficulty = 2
	// Hard — highest base reward (50 EXP / 20 gold).
	TaskDifficulty_TASK_DIFFICULTY_HARD TaskDifficulty = 3
)

// Enum value maps for TaskDifficulty.
var (
	TaskDifficulty_name = map[int32]string{
		0: "TASK_DIFFICULTY_UNSPECIFIED",
		1: "TASK_DIFFICULTY_EASY",
		2: "TASK_DIFFICULTY_MEDIUM",
		3: "TASK_DIFFICULTY_HARD",
	}
	TaskDifficulty_value = map[string]int32{
		"TASK_DIFFICULTY_UNSPECIFIED": 0,
		"TASK_DIFFICULTY_EASY":        1,
		"TASK_DIFFICULTY_MEDIUM":      2,
		"TASK_DIFFICULTY_HARD":        3,
	}
)

func (x TaskDifficulty) Enum() *TaskDifficulty {
	p := new(TaskDifficulty)
	*p = x
	return p
}

func (x TaskDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_v1_task_proto_enumTypes[1].Descriptor()
}

func (TaskDifficulty) Type() protoreflect.EnumType {
	return &file_api_task_v1_task_proto_enumTypes[1]
}

func (x TaskDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskDifficulty.Descriptor instead.
func (TaskDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{1}
}

// Task — a habit, daily or todo task owned by the current user.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short display title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Optional longer description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Task kind (habit / daily / todo).
	Type TaskType `protobuf:"varint,4,opt,name=type,proto3,enum=api.task.v1.TaskType" json:"type,omitempty"`
	// Difficulty that drives the base EXP/gold reward.
	Difficulty TaskDifficulty `protobuf:"varint,5,opt,name=difficulty,proto3,enum=api.task.v1.TaskDifficulty" json:"difficulty,omitempty"`
	// Free-form tags used for filtering.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// Whether the task is currently completed.
	IsCompleted bool `protobuf:"varint,7,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	// Completion time, unix millis; zero when not completed.
	CompletedAt int64 `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Due date, unix millis; zero when there is no due date.
	DueDate int64 `protobuf:"varint,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	// Weekday repeat mask for dailies: 0=Mon .. 6=Sun.
	RepeatDays []int32 `protobuf:"varint,10,rep,packed,name=repeat_days,json=repeatDays,proto3" json:"repeat_days,omitempty"`
	// Consecutive completion streak (one bump per day).
	Streak int32 `protobuf:"varint,11,opt,name=streak,proto3" json:"streak,omitempty"`
	// Date of the last day counted into the streak, unix millis.
	LastStreakDate int64 `protobuf:"varint,12,opt,name=last_streak_date,json=lastStreakDate,proto3" json:"last_streak_date,omitempty"`
	// Optional custom EXP reward overriding the difficulty-based value.
	CustomExpReward int32 `protobuf:"varint,13,opt,name=custom_exp_reward,json=customExpReward,proto3" json:"custom_exp_reward,omitempty"`
	// Optional custom gold reward overriding the difficulty-based value.
	CustomGoldReward int32 `protobuf:"varint,14,opt,name=custom_gold_reward,json=customGoldReward,proto3" json:"custom_gold_reward,omitempty"`
	// Optional priority label (e.g. "high" | "medium" | "low").
	Priority string `protobuf:"bytes,15,opt,name=priority,proto3" json:"priority,omitempty"`
	// HP penalty applied to the character when the task is missed.
	HpPenalty int32 `protobuf:"varint,16,opt,name=hp_penalty,json=hpPenalty,proto3" json:"hp_penalty,omitempty"`
	// Whether the task was skipped for the current period.
	IsSkipped bool `protobuf:"varint,17,opt,name=is_skipped,json=isSkipped,proto3" json:"is_skipped,omitempty"`
	// Creation time, unix millis.
	CreatedAt int64 `protobuf:"varint,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update time, unix millis.
	UpdatedAt     int64 `protobuf:"varint,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetDifficulty() TaskDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Task) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Task) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *Task) GetRepeatDays() []int32 {
	if x != nil {
		return x.RepeatDays
	}
	return nil
}

func (x *Task) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *Task) GetLastStreakDate() int64 {
	if x != nil {
		return x.LastStreakDate
	}
	return 0
}

func (x *Task) GetCustomExpReward() int32 {
	if x != nil {
		return x.CustomExpReward
	}
	return 0
}

func (x *Task) GetCustomGoldReward() int32 {
	if x != nil {
		return x.CustomGoldReward
	}
	return 0
}

func (x *Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Task) GetHpPenalty() int32 {
	if x != nil {
		return x.HpPenalty
	}
	return 0
}

func (x *Task) GetIsSkipped() bool {
	if x != nil {
		return x.IsSkipped
	}
	return false
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ListTasksRequest — filters for listing tasks.
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by task type.
	Type TaskType `protobuf:"varint,1,opt,name=type,proto3,enum=api.task.v1.TaskType" json:"type,omitempty"`
	// Optional filter by difficulty.
	Difficulty TaskDifficulty `protobuf:"varint,2,opt,name=difficulty,proto3,enum=api.task.v1.TaskDifficulty" json:"difficulty,omitempty"`
	// Optional filter by tags (matches any tag).
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// When true, only tasks due today are returned.
	OnlyDueToday bool `protobuf:"varint,4,opt,name=only_due_today,json=onlyDueToday,proto3" json:"only_due_today,omitempty"`
	// When true, completed tasks are included in the results.
	IncludeCompleted bool `protobuf:"varint,5,opt,name=include_completed,json=includeCompleted,proto3" json:"include_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *ListTasksRequest) GetDifficulty() TaskDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED
}

func (x *ListTasksRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTasksRequest) GetOnlyDueToday() bool {
	if x != nil {
		return x.OnlyDueToday
	}
	return false
}

func (x *ListTasksRequest) GetIncludeCompleted() bool {
	if x != nil {
		return x.IncludeCompleted
	}
	return false
}

// ListTasksReply — the matching tasks.
type ListTasksReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching tasks.
	Tasks         []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReply) Reset() {
	*x = ListTasksReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReply) ProtoMessage() {}

func (x *ListTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReply.ProtoReflect.Descriptor instead.
func (*ListTasksReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksReply) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// GetTaskRequest — id of the task to fetch.
type GetTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetTaskReply — the requested task.
type GetTaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested task.
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReply) Reset() {
	*x = GetTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReply) ProtoMessage() {}

func (x *GetTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReply.ProtoReflect.Descriptor instead.
func (*GetTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// CreateTaskRequest — task payload to create.
type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task to create; the server assigns the id.
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// CreateTaskReply — the created task with server-assigned fields.
type CreateTaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created task.
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReply) Reset() {
	*x = CreateTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReply) ProtoMessage() {}

func (x *CreateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReply.ProtoReflect.Descriptor instead.
func (*CreateTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// UpdateTaskRequest — id plus the full task payload to persist.
type UpdateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated task payload (full replace).
	Task          *Task `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// UpdateTaskReply — the updated task.
type UpdateTaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated task.
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskReply) Reset() {
	*x = UpdateTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskReply) ProtoMessage() {}

func (x *UpdateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskReply.ProtoReflect.Descriptor instead.
func (*UpdateTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// DeleteTaskRequest — id of the task to delete.
type DeleteTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteTaskReply — empty response for a successful delete.
type DeleteTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskReply) Reset() {
	*x = DeleteTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskReply) ProtoMessage() {}

func (x *DeleteTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskReply.ProtoReflect.Descriptor instead.
func (*DeleteTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{10}
}

// CompleteTaskRequest — id of the task to mark completed.
type CompleteTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CompleteTaskReply — completion result and granted rewards.
type CompleteTaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task with updated completion state.
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// EXP granted for completing this task (includes streak multiplier).
	ExpReward int32 `protobuf:"varint,2,opt,name=exp_reward,json=expReward,proto3" json:"exp_reward,omitempty"`
	// Gold granted for completing this task.
	GoldReward int32 `protobuf:"varint,3,opt,name=gold_reward,json=goldReward,proto3" json:"gold_reward,omitempty"`
	// HP change applied on completion (positive heals, negative damages).
	HpChange      int32 `protobuf:"varint,4,opt,name=hp_change,json=hpChange,proto3" json:"hp_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskReply) Reset() {
	*x = CompleteTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskReply) ProtoMessage() {}

func (x *CompleteTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskReply.ProtoReflect.Descriptor instead.
func (*CompleteTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *CompleteTaskReply) GetExpReward() int32 {
	if x != nil {
		return x.ExpReward
	}
	return 0
}

func (x *CompleteTaskReply) GetGoldReward() int32 {
	if x != nil {
		return x.GoldReward
	}
	return 0
}

func (x *CompleteTaskReply) GetHpChange() int32 {
	if x != nil {
		return x.HpChange
	}
	return 0
}

// SkipTaskRequest — id of the task to mark completed.
type SkipTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipTaskRequest) Reset() {
	*x = SkipTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipTaskRequest) ProtoMessage() {}

func (x *SkipTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipTaskRequest.ProtoReflect.Descriptor instead.
func (*SkipTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{13}
}

func (x *SkipTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SkipTaskReply — completion result and granted rewards.
type SkipTaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task with updated completion state.
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// EXP granted for completing this task (includes streak multiplier).
	ExpReward int32 `protobuf:"varint,2,opt,name=exp_reward,json=expReward,proto3" json:"exp_reward,omitempty"`
	// Gold granted for completing this task.
	GoldReward int32 `protobuf:"varint,3,opt,name=gold_reward,json=goldReward,proto3" json:"gold_reward,omitempty"`
	// HP change applied on completion (positive heals, negative damages).
	HpChange      int32 `protobuf:"varint,4,opt,name=hp_change,json=hpChange,proto3" json:"hp_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipTaskReply) Reset() {
	*x = SkipTaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipTaskReply) ProtoMessage() {}

func (x *SkipTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipTaskReply.ProtoReflect.Descriptor instead.
func (*SkipTaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{14}
}

func (x *SkipTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *SkipTaskReply) GetExpReward() int32 {
	if x != nil {
		return x.ExpReward
	}
	return 0
}

func (x *SkipTaskReply) GetGoldReward() int32 {
	if x != nil {
		return x.GoldReward
	}
	return 0
}

func (x *SkipTaskReply) GetHpChange() int32 {
	if x != nil {
		return x.HpChange
	}
	return 0
}

var File_api_task_v1_task_proto protoreflect.FileDescriptor

const file_api_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x16api/task/v1/task.proto\x12\vapi.task.v1\x1a\x1cgoogle/api/annotations.proto\"\x80\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.api.task.v1.TaskTypeR\x04type\x12;\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x1b.api.task.v1.TaskDifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12!\n" +
	"\fis_completed\x18\a \x01(\bR\visCompleted\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\x12\x19\n" +
	"\bdue_date\x18\t \x01(\x03R\adueDate\x12\x1f\n" +
	"\vrepeat_days\x18\n" +
	" \x03(\x05R\n" +
	"repeatDays\x12\x16\n" +
	"\x06streak\x18\v \x01(\x05R\x06streak\x12(\n" +
	"\x10last_streak_date\x18\f \x01(\x03R\x0elastStreakDate\x12*\n" +
	"\x11custom_exp_reward\x18\r \x01(\x05R\x0fcustomExpReward\x12,\n" +
	"\x12custom_gold_reward\x18\x0e \x01(\x05R\x10customGoldReward\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"hp_penalty\x18\x10 \x01(\x05R\thpPenalty\x12\x1d\n" +
	"\n" +
	"is_skipped\x18\x11 \x01(\bR\tisSkipped\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\x03R\tupdatedAt\"\xe1\x01\n" +
	"\x10ListTasksRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.api.task.v1.TaskTypeR\x04type\x12;\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\x0e2\x1b.api.task.v1.TaskDifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12$\n" +
	"\x0eonly_due_today\x18\x04 \x01(\bR\fonlyDueToday\x12+\n" +
	"\x11include_completed\x18\x05 \x01(\bR\x10includeCompleted\"9\n" +
	"\x0eListTasksReply\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.api.task.v1.TaskR\x05tasks\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\fGetTaskReply\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\":\n" +
	"\x11CreateTaskRequest\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\"8\n" +
	"\x0fCreateTaskReply\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\"J\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04task\x18\x02 \x01(\v2\x11.api.task.v1.TaskR\x04task\"8\n" +
	"\x0fUpdateTaskReply\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fDeleteTaskReply\"%\n" +
	"\x13CompleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x97\x01\n" +
	"\x11CompleteTaskReply\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\x12\x1d\n" +
	"\n" +
	"exp_reward\x18\x02 \x01(\x05R\texpReward\x12\x1f\n" +
	"\vgold_reward\x18\x03 \x01(\x05R\n" +
	"goldReward\x12\x1b\n" +
	"\thp_change\x18\x04 \x01(\x05R\bhpChange\"!\n" +
	"\x0fSkipTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\rSkipTaskReply\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.api.task.v1.TaskR\x04task\x12\x1d\n" +
	"\n" +
	"exp_reward\x18\x02 \x01(\x05R\texpReward\x12\x1f\n" +
	"\vgold_reward\x18\x03 \x01(\x05R\n" +
	"goldReward\x12\x1b\n" +
	"\thp_change\x18\x04 \x01(\x05R\bhpChange*c\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTASK_TYPE_HABIT\x10\x01\x12\x13\n" +
	"\x0fTASK_TYPE_DAILY\x10\x02\x12\x12\n" +
	"\x0eTASK_TYPE_TODO\x10\x03*\x81\x01\n" +
	"\x0eTaskDifficulty\x12\x1f\n" +
	"\x1bTASK_DIFFICULTY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_DIFFICULTY_EASY\x10\x01\x12\x1a\n" +
	"\x16TASK_DIFFICULTY_MEDIUM\x10\x02\x12\x18\n" +
	"\x14TASK_DIFFICULTY_HARD\x10\x032\xed\x05\n" +
	"\vTaskService\x12^\n" +
	"\tListTasks\x12\x1d.api.task.v1.ListTasksRequest\x1a\x1b.api.task.v1.ListTasksReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12]\n" +
	"\aGetTask\x12\x1b.api.task.v1.GetTaskRequest\x1a\x19.api.task.v1.GetTaskReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tasks/{id}\x12d\n" +
	"\n" +
	"CreateTask\x12\x1e.api.task.v1.CreateTaskRequest\x1a\x1c.api.task.v1.CreateTaskReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12i\n" +
	"\n" +
	"UpdateTask\x12\x1e.api.task.v1.UpdateTaskRequest\x1a\x1c.api.task.v1.UpdateTaskReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/tasks/{id}\x12f\n" +
	"\n" +
	"DeleteTask\x12\x1e.api.task.v1.DeleteTaskRequest\x1a\x1c.api.task.v1.DeleteTaskReply\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/tasks/{id}\x12x\n" +
	"\fCompleteTask\x12 .api.task.v1.CompleteTaskRequest\x1a\x1e.api.task.v1.CompleteTaskReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/tasks/{id}/complete\x12l\n" +
	"\bSkipTask\x12\x1c.api.task.v1.SkipTaskRequest\x1a\x1a.api.task.v1.SkipTaskReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/tasks/{id}/completeB.Z,github.com/habitforge/backend/api/task/v1;v1b\x06proto3"

var (
	file_api_task_v1_task_proto_rawDescOnce sync.Once
	file_api_task_v1_task_proto_rawDescData []byte
)

func file_api_task_v1_task_proto_rawDescGZIP() []byte {
	file_api_task_v1_task_proto_rawDescOnce.Do(func() {
		file_api_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_v1_task_proto_rawDesc), len(file_api_task_v1_task_proto_rawDesc)))
	})
	return file_api_task_v1_task_proto_rawDescData
}

var file_api_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_task_v1_task_proto_goTypes = []any{
	(TaskType)(0),               // 0: api.task.v1.TaskType
	(TaskDifficulty)(0),         // 1: api.task.v1.TaskDifficulty
	(*Task)(nil),                // 2: api.task.v1.Task
	(*ListTasksRequest)(nil),    // 3: api.task.v1.ListTasksRequest
	(*ListTasksReply)(nil),      // 4: api.task.v1.ListTasksReply
	(*GetTaskRequest)(nil),      // 5: api.task.v1.GetTaskRequest
	(*GetTaskReply)(nil),        // 6: api.task.v1.GetTaskReply
	(*CreateTaskRequest)(nil),   // 7: api.task.v1.CreateTaskRequest
	(*CreateTaskReply)(nil),     // 8: api.task.v1.CreateTaskReply
	(*UpdateTaskRequest)(nil),   // 9: api.task.v1.UpdateTaskRequest
	(*UpdateTaskReply)(nil),     // 10: api.task.v1.UpdateTaskReply
	(*DeleteTaskRequest)(nil),   // 11: api.task.v1.DeleteTaskRequest
	(*DeleteTaskReply)(nil),     // 12: api.task.v1.DeleteTaskReply
	(*CompleteTaskRequest)(nil), // 13: api.task.v1.CompleteTaskRequest
	(*CompleteTaskReply)(nil),   // 14: api.task.v1.CompleteTaskReply
	(*SkipTaskRequest)(nil),     // 15: api.task.v1.SkipTaskRequest
	(*SkipTaskReply)(nil),       // 16: api.task.v1.SkipTaskReply
}
var file_api_task_v1_task_proto_depIdxs = []int32{
	0,  // 0: api.task.v1.Task.type:type_name -> api.task.v1.TaskType
	1,  // 1: api.task.v1.Task.difficulty:type_name -> api.task.v1.TaskDifficulty
	0,  // 2: api.task.v1.ListTasksRequest.type:type_name -> api.task.v1.TaskType
	1,  // 3: api.task.v1.ListTasksRequest.difficulty:type_name -> api.task.v1.TaskDifficulty
	2,  // 4: api.task.v1.ListTasksReply.tasks:type_name -> api.task.v1.Task
	2,  // 5: api.task.v1.GetTaskReply.task:type_name -> api.task.v1.Task
	2,  // 6: api.task.v1.CreateTaskRequest.task:type_name -> api.task.v1.Task
	2,  // 7: api.task.v1.CreateTaskReply.task:type_name -> api.task.v1.Task
	2,  // 8: api.task.v1.UpdateTaskRequest.task:type_name -> api.task.v1.Task
	2,  // 9: api.task.v1.UpdateTaskReply.task:type_name -> api.task.v1.Task
	2,  // 10: api.task.v1.CompleteTaskReply.task:type_name -> api.task.v1.Task
	2,  // 11: api.task.v1.SkipTaskReply.task:type_name -> api.task.v1.Task
	3,  // 12: api.task.v1.TaskService.ListTasks:input_type -> api.task.v1.ListTasksRequest
	5,  // 13: api.task.v1.TaskService.GetTask:input_type -> api.task.v1.GetTaskRequest
	7,  // 14: api.task.v1.TaskService.CreateTask:input_type -> api.task.v1.CreateTaskRequest
	9,  // 15: api.task.v1.TaskService.UpdateTask:input_type -> api.task.v1.UpdateTaskRequest
	11, // 16: api.task.v1.TaskService.DeleteTask:input_type -> api.task.v1.DeleteTaskRequest
	13, // 17: api.task.v1.TaskService.CompleteTask:input_type -> api.task.v1.CompleteTaskRequest
	15, // 18: api.task.v1.TaskService.SkipTask:input_type -> api.task.v1.SkipTaskRequest
	4,  // 19: api.task.v1.TaskService.ListTasks:output_type -> api.task.v1.ListTasksReply
	6,  // 20: api.task.v1.TaskService.GetTask:output_type -> api.task.v1.GetTaskReply
	8,  // 21: api.task.v1.TaskService.CreateTask:output_type -> api.task.v1.CreateTaskReply
	10, // 22: api.task.v1.TaskService.UpdateTask:output_type -> api.task.v1.UpdateTaskReply
	12, // 23: api.task.v1.TaskService.DeleteTask:output_type -> api.task.v1.DeleteTaskReply
	14, // 24: api.task.v1.TaskService.CompleteTask:output_type -> api.task.v1.CompleteTaskReply
	16, // 25: api.task.v1.TaskService.SkipTask:output_type -> api.task.v1.SkipTaskReply
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_task_v1_task_proto_init() }
func file_api_task_v1_task_proto_init() {
	if File_api_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_v1_task_proto_rawDesc), len(file_api_task_v1_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_v1_task_proto_goTypes,
		DependencyIndexes: file_api_task_v1_task_proto_depIdxs,
		EnumInfos:         file_api_task_v1_task_proto_enumTypes,
		MessageInfos:      file_api_task_v1_task_proto_msgTypes,
	}.Build()
	File_api_task_v1_task_proto = out.File
	file_api_task_v1_task_proto_goTypes = nil
	file_api_task_v1_task_proto_depIdxs = nil
}
