// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/task/v1/task_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskErrorReason — business error codes for the task domain.
type TaskErrorReason int32

const (
	TaskErrorReason_TASK_ALREADY_EXISTS TaskErrorReason = 0
	TaskErrorReason_TASK_NOT_FOUND      TaskErrorReason = 1
)

// Enum value maps for TaskErrorReason.
var (
	TaskErrorReason_name = map[int32]string{
		0: "TASK_ALREADY_EXISTS",
		1: "TASK_NOT_FOUND",
	}
	TaskErrorReason_value = map[string]int32{
		"TASK_ALREADY_EXISTS": 0,
		"TASK_NOT_FOUND":      1,
	}
)

func (x TaskErrorReason) Enum() *TaskErrorReason {
	p := new(TaskErrorReason)
	*p = x
	return p
}

func (x TaskErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_v1_task_error_proto_enumTypes[0].Descriptor()
}

func (TaskErrorReason) Type() protoreflect.EnumType {
	return &file_api_task_v1_task_error_proto_enumTypes[0]
}

func (x TaskErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskErrorReason.Descriptor instead.
func (TaskErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_task_v1_task_error_proto_rawDescGZIP(), []int{0}
}

var File_api_task_v1_task_error_proto protoreflect.FileDescriptor

const file_api_task_v1_task_error_proto_rawDesc = "" +
	"\n" +
	"\x1capi/task/v1/task_error.proto\x12\vapi.task.v1\x1a\x13errors/errors.proto*P\n" +
	"\x0fTaskErrorReason\x12\x1d\n" +
	"\x13TASK_ALREADY_EXISTS\x10\x00\x1a\x04\xa8E\x99\x03\x12\x18\n" +
	"\x0eTASK_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\xf4\x03B.Z,github.com/habitforge/backend/api/task/v1;v1b\x06proto3"

var (
	file_api_task_v1_task_error_proto_rawDescOnce sync.Once
	file_api_task_v1_task_error_proto_rawDescData []byte
)

func file_api_task_v1_task_error_proto_rawDescGZIP() []byte {
	file_api_task_v1_task_error_proto_rawDescOnce.Do(func() {
		file_api_task_v1_task_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_v1_task_error_proto_rawDesc), len(file_api_task_v1_task_error_proto_rawDesc)))
	})
	return file_api_task_v1_task_error_proto_rawDescData
}

var file_api_task_v1_task_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_task_v1_task_error_proto_goTypes = []any{
	(TaskErrorReason)(0), // 0: api.task.v1.TaskErrorReason
}
var file_api_task_v1_task_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_task_v1_task_error_proto_init() }
func file_api_task_v1_task_error_proto_init() {
	if File_api_task_v1_task_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_v1_task_error_proto_rawDesc), len(file_api_task_v1_task_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_task_v1_task_error_proto_goTypes,
		DependencyIndexes: file_api_task_v1_task_error_proto_depIdxs,
		EnumInfos:         file_api_task_v1_task_error_proto_enumTypes,
	}.Build()
	File_api_task_v1_task_error_proto = out.File
	file_api_task_v1_task_error_proto_goTypes = nil
	file_api_task_v1_task_error_proto_depIdxs = nil
}
