// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/character/v1/character.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatType — character attributes.
type StatType int32

const (
	StatType_STAT_TYPE_UNSPECIFIED  StatType = 0
	StatType_STAT_TYPE_STRENGTH     StatType = 1
	StatType_STAT_TYPE_INTELLIGENCE StatType = 2
	StatType_STAT_TYPE_AGILITY      StatType = 3
	StatType_STAT_TYPE_DEFENSE      StatType = 4
	StatType_STAT_TYPE_VITALITY     StatType = 5
	StatType_STAT_TYPE_LUCK         StatType = 6
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "STAT_TYPE_UNSPECIFIED",
		1: "STAT_TYPE_STRENGTH",
		2: "STAT_TYPE_INTELLIGENCE",
		3: "STAT_TYPE_AGILITY",
		4: "STAT_TYPE_DEFENSE",
		5: "STAT_TYPE_VITALITY",
		6: "STAT_TYPE_LUCK",
	}
	StatType_value = map[string]int32{
		"STAT_TYPE_UNSPECIFIED":  0,
		"STAT_TYPE_STRENGTH":     1,
		"STAT_TYPE_INTELLIGENCE": 2,
		"STAT_TYPE_AGILITY":      3,
		"STAT_TYPE_DEFENSE":      4,
		"STAT_TYPE_VITALITY":     5,
		"STAT_TYPE_LUCK":         6,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_character_v1_character_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_api_character_v1_character_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{0}
}

type CharacterStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	Intelligence  int32                  `protobuf:"varint,2,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Agility       int32                  `protobuf:"varint,3,opt,name=agility,proto3" json:"agility,omitempty"`
	Defense       int32                  `protobuf:"varint,4,opt,name=defense,proto3" json:"defense,omitempty"`
	Vitality      int32                  `protobuf:"varint,5,opt,name=vitality,proto3" json:"vitality,omitempty"`
	Luck          int32                  `protobuf:"varint,6,opt,name=luck,proto3" json:"luck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterStats) Reset() {
	*x = CharacterStats{}
	mi := &file_api_character_v1_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStats) ProtoMessage() {}

func (x *CharacterStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStats.ProtoReflect.Descriptor instead.
func (*CharacterStats) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterStats) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *CharacterStats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *CharacterStats) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *CharacterStats) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CharacterStats) GetVitality() int32 {
	if x != nil {
		return x.Vitality
	}
	return 0
}

func (x *CharacterStats) GetLuck() int32 {
	if x != nil {
		return x.Luck
	}
	return 0
}

type Character struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Class               string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"` // "warrior" | "mage" | "ranger"
	Level               int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	CurrentExp          int64                  `protobuf:"varint,4,opt,name=current_exp,json=currentExp,proto3" json:"current_exp,omitempty"`
	CurrentHp           int32                  `protobuf:"varint,5,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	BaseStats           *CharacterStats        `protobuf:"bytes,6,opt,name=base_stats,json=baseStats,proto3" json:"base_stats,omitempty"`
	AvailableStatPoints int32                  `protobuf:"varint,7,opt,name=available_stat_points,json=availableStatPoints,proto3" json:"available_stat_points,omitempty"`
	Equipment           map[string]string      `protobuf:"bytes,8,rep,name=equipment,proto3" json:"equipment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // weapon/helmet/armor/accessory -> shop item id
	IsDead              bool                   `protobuf:"varint,9,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	DeathRecoveryUntil  int64                  `protobuf:"varint,10,opt,name=death_recovery_until,json=deathRecoveryUntil,proto3" json:"death_recovery_until,omitempty"` // unix millis
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_api_character_v1_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{1}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetCurrentExp() int64 {
	if x != nil {
		return x.CurrentExp
	}
	return 0
}

func (x *Character) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *Character) GetBaseStats() *CharacterStats {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *Character) GetAvailableStatPoints() int32 {
	if x != nil {
		return x.AvailableStatPoints
	}
	return 0
}

func (x *Character) GetEquipment() map[string]string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Character) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

func (x *Character) GetDeathRecoveryUntil() int64 {
	if x != nil {
		return x.DeathRecoveryUntil
	}
	return 0
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_api_character_v1_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{2}
}

type GetCharacterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterReply) Reset() {
	*x = GetCharacterReply{}
	mi := &file_api_character_v1_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterReply) ProtoMessage() {}

func (x *GetCharacterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterReply.ProtoReflect.Descriptor instead.
func (*GetCharacterReply) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterReply) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type UpdateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRequest) Reset() {
	*x = UpdateCharacterRequest{}
	mi := &file_api_character_v1_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRequest) ProtoMessage() {}

func (x *UpdateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCharacterRequest) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type UpdateCharacterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterReply) Reset() {
	*x = UpdateCharacterReply{}
	mi := &file_api_character_v1_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterReply) ProtoMessage() {}

func (x *UpdateCharacterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterReply.ProtoReflect.Descriptor instead.
func (*UpdateCharacterReply) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCharacterReply) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type AllocateStatPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          StatType               `protobuf:"varint,1,opt,name=stat,proto3,enum=api.character.v1.StatType" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateStatPointRequest) Reset() {
	*x = AllocateStatPointRequest{}
	mi := &file_api_character_v1_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateStatPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStatPointRequest) ProtoMessage() {}

func (x *AllocateStatPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStatPointRequest.ProtoReflect.Descriptor instead.
func (*AllocateStatPointRequest) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateStatPointRequest) GetStat() StatType {
	if x != nil {
		return x.Stat
	}
	return StatType_STAT_TYPE_UNSPECIFIED
}

type AllocateStatPointReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateStatPointReply) Reset() {
	*x = AllocateStatPointReply{}
	mi := &file_api_character_v1_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateStatPointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStatPointReply) ProtoMessage() {}

func (x *AllocateStatPointReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStatPointReply.ProtoReflect.Descriptor instead.
func (*AllocateStatPointReply) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{7}
}

func (x *AllocateStatPointReply) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type ReviveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviveRequest) Reset() {
	*x = ReviveRequest{}
	mi := &file_api_character_v1_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviveRequest) ProtoMessage() {}

func (x *ReviveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviveRequest.ProtoReflect.Descriptor instead.
func (*ReviveRequest) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{8}
}

type ReviveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviveReply) Reset() {
	*x = ReviveReply{}
	mi := &file_api_character_v1_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviveReply) ProtoMessage() {}

func (x *ReviveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_character_v1_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviveReply.ProtoReflect.Descriptor instead.
func (*ReviveReply) Descriptor() ([]byte, []int) {
	return file_api_character_v1_character_proto_rawDescGZIP(), []int{9}
}

func (x *ReviveReply) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

var File_api_character_v1_character_proto protoreflect.FileDescriptor

const file_api_character_v1_character_proto_rawDesc = "" +
	"\n" +
	" api/character/v1/character.proto\x12\x10api.character.v1\x1a\x1cgoogle/api/annotations.proto\"\xb4\x01\n" +
	"\x0eCharacterStats\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\"\n" +
	"\fintelligence\x18\x02 \x01(\x05R\fintelligence\x12\x18\n" +
	"\aagility\x18\x03 \x01(\x05R\aagility\x12\x18\n" +
	"\adefense\x18\x04 \x01(\x05R\adefense\x12\x1a\n" +
	"\bvitality\x18\x05 \x01(\x05R\bvitality\x12\x12\n" +
	"\x04luck\x18\x06 \x01(\x05R\x04luck\"\xcf\x03\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1f\n" +
	"\vcurrent_exp\x18\x04 \x01(\x03R\n" +
	"currentExp\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x05 \x01(\x05R\tcurrentHp\x12?\n" +
	"\n" +
	"base_stats\x18\x06 \x01(\v2 .api.character.v1.CharacterStatsR\tbaseStats\x122\n" +
	"\x15available_stat_points\x18\a \x01(\x05R\x13availableStatPoints\x12H\n" +
	"\tequipment\x18\b \x03(\v2*.api.character.v1.Character.EquipmentEntryR\tequipment\x12\x17\n" +
	"\ais_dead\x18\t \x01(\bR\x06isDead\x120\n" +
	"\x14death_recovery_until\x18\n" +
	" \x01(\x03R\x12deathRecoveryUntil\x1a<\n" +
	"\x0eEquipmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13GetCharacterRequest\"N\n" +
	"\x11GetCharacterReply\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.api.character.v1.CharacterR\tcharacter\"S\n" +
	"\x16UpdateCharacterRequest\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.api.character.v1.CharacterR\tcharacter\"Q\n" +
	"\x14UpdateCharacterReply\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.api.character.v1.CharacterR\tcharacter\"J\n" +
	"\x18AllocateStatPointRequest\x12.\n" +
	"\x04stat\x18\x01 \x01(\x0e2\x1a.api.character.v1.StatTypeR\x04stat\"S\n" +
	"\x16AllocateStatPointReply\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.api.character.v1.CharacterR\tcharacter\"\x0f\n" +
	"\rReviveRequest\"H\n" +
	"\vReviveReply\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.api.character.v1.CharacterR\tcharacter*\xb3\x01\n" +
	"\bStatType\x12\x19\n" +
	"\x15STAT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STAT_TYPE_STRENGTH\x10\x01\x12\x1a\n" +
	"\x16STAT_TYPE_INTELLIGENCE\x10\x02\x12\x15\n" +
	"\x11STAT_TYPE_AGILITY\x10\x03\x12\x15\n" +
	"\x11STAT_TYPE_DEFENSE\x10\x04\x12\x16\n" +
	"\x12STAT_TYPE_VITALITY\x10\x05\x12\x12\n" +
	"\x0eSTAT_TYPE_LUCK\x10\x062\x95\x04\n" +
	"\x10CharacterService\x12u\n" +
	"\fGetCharacter\x12%.api.character.v1.GetCharacterRequest\x1a#.api.character.v1.GetCharacterReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/character\x12\x81\x01\n" +
	"\x0fUpdateCharacter\x12(.api.character.v1.UpdateCharacterRequest\x1a&.api.character.v1.UpdateCharacterReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/character\x12\x96\x01\n" +
	"\x11AllocateStatPoint\x12*.api.character.v1.AllocateStatPointRequest\x1a(.api.character.v1.AllocateStatPointReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/character/stats/allocate\x12m\n" +
	"\x06Revive\x12\x1f.api.character.v1.ReviveRequest\x1a\x1d.api.character.v1.ReviveReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/character/reviveB3Z1github.com/habitforge/backend/api/character/v1;v1b\x06proto3"

var (
	file_api_character_v1_character_proto_rawDescOnce sync.Once
	file_api_character_v1_character_proto_rawDescData []byte
)

func file_api_character_v1_character_proto_rawDescGZIP() []byte {
	file_api_character_v1_character_proto_rawDescOnce.Do(func() {
		file_api_character_v1_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_character_v1_character_proto_rawDesc), len(file_api_character_v1_character_proto_rawDesc)))
	})
	return file_api_character_v1_character_proto_rawDescData
}

var file_api_character_v1_character_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_character_v1_character_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_character_v1_character_proto_goTypes = []any{
	(StatType)(0),                    // 0: api.character.v1.StatType
	(*CharacterStats)(nil),           // 1: api.character.v1.CharacterStats
	(*Character)(nil),                // 2: api.character.v1.Character
	(*GetCharacterRequest)(nil),      // 3: api.character.v1.GetCharacterRequest
	(*GetCharacterReply)(nil),        // 4: api.character.v1.GetCharacterReply
	(*UpdateCharacterRequest)(nil),   // 5: api.character.v1.UpdateCharacterRequest
	(*UpdateCharacterReply)(nil),     // 6: api.character.v1.UpdateCharacterReply
	(*AllocateStatPointRequest)(nil), // 7: api.character.v1.AllocateStatPointRequest
	(*AllocateStatPointReply)(nil),   // 8: api.character.v1.AllocateStatPointReply
	(*ReviveRequest)(nil),            // 9: api.character.v1.ReviveRequest
	(*ReviveReply)(nil),              // 10: api.character.v1.ReviveReply
	nil,                              // 11: api.character.v1.Character.EquipmentEntry
}
var file_api_character_v1_character_proto_depIdxs = []int32{
	1,  // 0: api.character.v1.Character.base_stats:type_name -> api.character.v1.CharacterStats
	11, // 1: api.character.v1.Character.equipment:type_name -> api.character.v1.Character.EquipmentEntry
	2,  // 2: api.character.v1.GetCharacterReply.character:type_name -> api.character.v1.Character
	2,  // 3: api.character.v1.UpdateCharacterRequest.character:type_name -> api.character.v1.Character
	2,  // 4: api.character.v1.UpdateCharacterReply.character:type_name -> api.character.v1.Character
	0,  // 5: api.character.v1.AllocateStatPointRequest.stat:type_name -> api.character.v1.StatType
	2,  // 6: api.character.v1.AllocateStatPointReply.character:type_name -> api.character.v1.Character
	2,  // 7: api.character.v1.ReviveReply.character:type_name -> api.character.v1.Character
	3,  // 8: api.character.v1.CharacterService.GetCharacter:input_type -> api.character.v1.GetCharacterRequest
	5,  // 9: api.character.v1.CharacterService.UpdateCharacter:input_type -> api.character.v1.UpdateCharacterRequest
	7,  // 10: api.character.v1.CharacterService.AllocateStatPoint:input_type -> api.character.v1.AllocateStatPointRequest
	9,  // 11: api.character.v1.CharacterService.Revive:input_type -> api.character.v1.ReviveRequest
	4,  // 12: api.character.v1.CharacterService.GetCharacter:output_type -> api.character.v1.GetCharacterReply
	6,  // 13: api.character.v1.CharacterService.UpdateCharacter:output_type -> api.character.v1.UpdateCharacterReply
	8,  // 14: api.character.v1.CharacterService.AllocateStatPoint:output_type -> api.character.v1.AllocateStatPointReply
	10, // 15: api.character.v1.CharacterService.Revive:output_type -> api.character.v1.ReviveReply
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_character_v1_character_proto_init() }
func file_api_character_v1_character_proto_init() {
	if File_api_character_v1_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_character_v1_character_proto_rawDesc), len(file_api_character_v1_character_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_character_v1_character_proto_goTypes,
		DependencyIndexes: file_api_character_v1_character_proto_depIdxs,
		EnumInfos:         file_api_character_v1_character_proto_enumTypes,
		MessageInfos:      file_api_character_v1_character_proto_msgTypes,
	}.Build()
	File_api_character_v1_character_proto = out.File
	file_api_character_v1_character_proto_goTypes = nil
	file_api_character_v1_character_proto_depIdxs = nil
}
