// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: character/v1/character.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CharacterService_GetCharacter_FullMethodName      = "/api.character.v1.CharacterService/GetCharacter"
	CharacterService_UpdateCharacter_FullMethodName   = "/api.character.v1.CharacterService/UpdateCharacter"
	CharacterService_AllocateStatPoint_FullMethodName = "/api.character.v1.CharacterService/AllocateStatPoint"
	CharacterService_Revive_FullMethodName            = "/api.character.v1.CharacterService/Revive"
)

// CharacterServiceClient is the client API for CharacterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CharacterService — RPG character state: class, level, EXP, HP, stats, equipment.
type CharacterServiceClient interface {
	// GetCharacter returns the current user's character.
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterReply, error)
	// UpdateCharacter replaces the character state (level/exp/hp/stats/equipment).
	UpdateCharacter(ctx context.Context, in *UpdateCharacterRequest, opts ...grpc.CallOption) (*UpdateCharacterReply, error)
	// AllocateStatPoint spends one available stat point on an attribute.
	AllocateStatPoint(ctx context.Context, in *AllocateStatPointRequest, opts ...grpc.CallOption) (*AllocateStatPointReply, error)
	// Revive revives a dead character (e.g. after the recovery timer).
	Revive(ctx context.Context, in *ReviveRequest, opts ...grpc.CallOption) (*ReviveReply, error)
}

type characterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharacterServiceClient(cc grpc.ClientConnInterface) CharacterServiceClient {
	return &characterServiceClient{cc}
}

func (c *characterServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCharacterReply)
	err := c.cc.Invoke(ctx, CharacterService_GetCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterServiceClient) UpdateCharacter(ctx context.Context, in *UpdateCharacterRequest, opts ...grpc.CallOption) (*UpdateCharacterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCharacterReply)
	err := c.cc.Invoke(ctx, CharacterService_UpdateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterServiceClient) AllocateStatPoint(ctx context.Context, in *AllocateStatPointRequest, opts ...grpc.CallOption) (*AllocateStatPointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateStatPointReply)
	err := c.cc.Invoke(ctx, CharacterService_AllocateStatPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterServiceClient) Revive(ctx context.Context, in *ReviveRequest, opts ...grpc.CallOption) (*ReviveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviveReply)
	err := c.cc.Invoke(ctx, CharacterService_Revive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharacterServiceServer is the server API for CharacterService service.
// All implementations must embed UnimplementedCharacterServiceServer
// for forward compatibility.
//
// CharacterService — RPG character state: class, level, EXP, HP, stats, equipment.
type CharacterServiceServer interface {
	// GetCharacter returns the current user's character.
	GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterReply, error)
	// UpdateCharacter replaces the character state (level/exp/hp/stats/equipment).
	UpdateCharacter(context.Context, *UpdateCharacterRequest) (*UpdateCharacterReply, error)
	// AllocateStatPoint spends one available stat point on an attribute.
	AllocateStatPoint(context.Context, *AllocateStatPointRequest) (*AllocateStatPointReply, error)
	// Revive revives a dead character (e.g. after the recovery timer).
	Revive(context.Context, *ReviveRequest) (*ReviveReply, error)
	mustEmbedUnimplementedCharacterServiceServer()
}

// UnimplementedCharacterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCharacterServiceServer struct{}

func (UnimplementedCharacterServiceServer) GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCharacter not implemented")
}
func (UnimplementedCharacterServiceServer) UpdateCharacter(context.Context, *UpdateCharacterRequest) (*UpdateCharacterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCharacter not implemented")
}
func (UnimplementedCharacterServiceServer) AllocateStatPoint(context.Context, *AllocateStatPointRequest) (*AllocateStatPointReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateStatPoint not implemented")
}
func (UnimplementedCharacterServiceServer) Revive(context.Context, *ReviveRequest) (*ReviveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Revive not implemented")
}
func (UnimplementedCharacterServiceServer) mustEmbedUnimplementedCharacterServiceServer() {}
func (UnimplementedCharacterServiceServer) testEmbeddedByValue()                          {}

// UnsafeCharacterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharacterServiceServer will
// result in compilation errors.
type UnsafeCharacterServiceServer interface {
	mustEmbedUnimplementedCharacterServiceServer()
}

func RegisterCharacterServiceServer(s grpc.ServiceRegistrar, srv CharacterServiceServer) {
	// If the following call panics, it indicates UnimplementedCharacterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CharacterService_ServiceDesc, srv)
}

func _CharacterService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_GetCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterService_UpdateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).UpdateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_UpdateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).UpdateCharacter(ctx, req.(*UpdateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterService_AllocateStatPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateStatPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).AllocateStatPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_AllocateStatPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).AllocateStatPoint(ctx, req.(*AllocateStatPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterService_Revive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).Revive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_Revive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).Revive(ctx, req.(*ReviveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CharacterService_ServiceDesc is the grpc.ServiceDesc for CharacterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharacterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.character.v1.CharacterService",
	HandlerType: (*CharacterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCharacter",
			Handler:    _CharacterService_GetCharacter_Handler,
		},
		{
			MethodName: "UpdateCharacter",
			Handler:    _CharacterService_UpdateCharacter_Handler,
		},
		{
			MethodName: "AllocateStatPoint",
			Handler:    _CharacterService_AllocateStatPoint_Handler,
		},
		{
			MethodName: "Revive",
			Handler:    _CharacterService_Revive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "character/v1/character.proto",
}
