// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/character/v1/character.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCharacterServiceAllocateStatPoint = "/api.character.v1.CharacterService/AllocateStatPoint"
const OperationCharacterServiceGetCharacter = "/api.character.v1.CharacterService/GetCharacter"
const OperationCharacterServiceRevive = "/api.character.v1.CharacterService/Revive"
const OperationCharacterServiceUpdateCharacter = "/api.character.v1.CharacterService/UpdateCharacter"

type CharacterServiceHTTPServer interface {
	// AllocateStatPoint AllocateStatPoint spends one available stat point on an attribute.
	AllocateStatPoint(context.Context, *AllocateStatPointRequest) (*AllocateStatPointReply, error)
	// GetCharacter GetCharacter returns the current user's character.
	GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterReply, error)
	// Revive Revive revives a dead character (e.g. after the recovery timer).
	Revive(context.Context, *ReviveRequest) (*ReviveReply, error)
	// UpdateCharacter UpdateCharacter replaces the character state (level/exp/hp/stats/equipment).
	UpdateCharacter(context.Context, *UpdateCharacterRequest) (*UpdateCharacterReply, error)
}

func RegisterCharacterServiceHTTPServer(s *http.Server, srv CharacterServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/character", _CharacterService_GetCharacter0_HTTP_Handler(srv))
	r.PUT("/api/v1/character", _CharacterService_UpdateCharacter0_HTTP_Handler(srv))
	r.POST("/api/v1/character/stats/allocate", _CharacterService_AllocateStatPoint0_HTTP_Handler(srv))
	r.POST("/api/v1/character/revive", _CharacterService_Revive0_HTTP_Handler(srv))
}

func _CharacterService_GetCharacter0_HTTP_Handler(srv CharacterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCharacterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCharacterServiceGetCharacter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCharacter(ctx, req.(*GetCharacterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCharacterReply)
		return ctx.Result(200, reply)
	}
}

func _CharacterService_UpdateCharacter0_HTTP_Handler(srv CharacterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCharacterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCharacterServiceUpdateCharacter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCharacter(ctx, req.(*UpdateCharacterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCharacterReply)
		return ctx.Result(200, reply)
	}
}

func _CharacterService_AllocateStatPoint0_HTTP_Handler(srv CharacterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AllocateStatPointRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCharacterServiceAllocateStatPoint)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AllocateStatPoint(ctx, req.(*AllocateStatPointRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AllocateStatPointReply)
		return ctx.Result(200, reply)
	}
}

func _CharacterService_Revive0_HTTP_Handler(srv CharacterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReviveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCharacterServiceRevive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Revive(ctx, req.(*ReviveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReviveReply)
		return ctx.Result(200, reply)
	}
}

type CharacterServiceHTTPClient interface {
	// AllocateStatPoint AllocateStatPoint spends one available stat point on an attribute.
	AllocateStatPoint(ctx context.Context, req *AllocateStatPointRequest, opts ...http.CallOption) (rsp *AllocateStatPointReply, err error)
	// GetCharacter GetCharacter returns the current user's character.
	GetCharacter(ctx context.Context, req *GetCharacterRequest, opts ...http.CallOption) (rsp *GetCharacterReply, err error)
	// Revive Revive revives a dead character (e.g. after the recovery timer).
	Revive(ctx context.Context, req *ReviveRequest, opts ...http.CallOption) (rsp *ReviveReply, err error)
	// UpdateCharacter UpdateCharacter replaces the character state (level/exp/hp/stats/equipment).
	UpdateCharacter(ctx context.Context, req *UpdateCharacterRequest, opts ...http.CallOption) (rsp *UpdateCharacterReply, err error)
}

type CharacterServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCharacterServiceHTTPClient(client *http.Client) CharacterServiceHTTPClient {
	return &CharacterServiceHTTPClientImpl{client}
}

// AllocateStatPoint AllocateStatPoint spends one available stat point on an attribute.
func (c *CharacterServiceHTTPClientImpl) AllocateStatPoint(ctx context.Context, in *AllocateStatPointRequest, opts ...http.CallOption) (*AllocateStatPointReply, error) {
	var out AllocateStatPointReply
	pattern := "/api/v1/character/stats/allocate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCharacterServiceAllocateStatPoint))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCharacter GetCharacter returns the current user's character.
func (c *CharacterServiceHTTPClientImpl) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...http.CallOption) (*GetCharacterReply, error) {
	var out GetCharacterReply
	pattern := "/api/v1/character"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCharacterServiceGetCharacter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Revive Revive revives a dead character (e.g. after the recovery timer).
func (c *CharacterServiceHTTPClientImpl) Revive(ctx context.Context, in *ReviveRequest, opts ...http.CallOption) (*ReviveReply, error) {
	var out ReviveReply
	pattern := "/api/v1/character/revive"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCharacterServiceRevive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCharacter UpdateCharacter replaces the character state (level/exp/hp/stats/equipment).
func (c *CharacterServiceHTTPClientImpl) UpdateCharacter(ctx context.Context, in *UpdateCharacterRequest, opts ...http.CallOption) (*UpdateCharacterReply, error) {
	var out UpdateCharacterReply
	pattern := "/api/v1/character"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCharacterServiceUpdateCharacter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
