// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/achievement/v1/achievement.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAchievementServiceListAchievements = "/api.achievement.v1.AchievementService/ListAchievements"
const OperationAchievementServiceUnlock = "/api.achievement.v1.AchievementService/Unlock"

type AchievementServiceHTTPServer interface {
	// ListAchievements ListAchievements lists all achievements with unlock state.
	ListAchievements(context.Context, *ListAchievementsRequest) (*ListAchievementsReply, error)
	// Unlock Unlock claims an achievement and grants its gem reward.
	Unlock(context.Context, *UnlockRequest) (*UnlockReply, error)
}

func RegisterAchievementServiceHTTPServer(s *http.Server, srv AchievementServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/achievements", _AchievementService_ListAchievements0_HTTP_Handler(srv))
	r.POST("/api/v1/achievements/{id}/unlock", _AchievementService_Unlock0_HTTP_Handler(srv))
}

func _AchievementService_ListAchievements0_HTTP_Handler(srv AchievementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAchievementsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAchievementServiceListAchievements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAchievements(ctx, req.(*ListAchievementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAchievementsReply)
		return ctx.Result(200, reply)
	}
}

func _AchievementService_Unlock0_HTTP_Handler(srv AchievementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnlockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAchievementServiceUnlock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Unlock(ctx, req.(*UnlockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnlockReply)
		return ctx.Result(200, reply)
	}
}

type AchievementServiceHTTPClient interface {
	// ListAchievements ListAchievements lists all achievements with unlock state.
	ListAchievements(ctx context.Context, req *ListAchievementsRequest, opts ...http.CallOption) (rsp *ListAchievementsReply, err error)
	// Unlock Unlock claims an achievement and grants its gem reward.
	Unlock(ctx context.Context, req *UnlockRequest, opts ...http.CallOption) (rsp *UnlockReply, err error)
}

type AchievementServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAchievementServiceHTTPClient(client *http.Client) AchievementServiceHTTPClient {
	return &AchievementServiceHTTPClientImpl{client}
}

// ListAchievements ListAchievements lists all achievements with unlock state.
func (c *AchievementServiceHTTPClientImpl) ListAchievements(ctx context.Context, in *ListAchievementsRequest, opts ...http.CallOption) (*ListAchievementsReply, error) {
	var out ListAchievementsReply
	pattern := "/api/v1/achievements"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAchievementServiceListAchievements))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Unlock Unlock claims an achievement and grants its gem reward.
func (c *AchievementServiceHTTPClientImpl) Unlock(ctx context.Context, in *UnlockRequest, opts ...http.CallOption) (*UnlockReply, error) {
	var out UnlockReply
	pattern := "/api/v1/achievements/{id}/unlock"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAchievementServiceUnlock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
