// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/achievement/v1/achievement.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Achievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConditionType string                 `protobuf:"bytes,4,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"` // e.g. "tasks_completed" | "streak" | "level"
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	IsUnlocked    bool                   `protobuf:"varint,7,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	UnlockedAt    int64                  `protobuf:"varint,8,opt,name=unlocked_at,json=unlockedAt,proto3" json:"unlocked_at,omitempty"` // unix millis
	GemReward     int32                  `protobuf:"varint,9,opt,name=gem_reward,json=gemReward,proto3" json:"gem_reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Achievement) Reset() {
	*x = Achievement{}
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Achievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Achievement) ProtoMessage() {}

func (x *Achievement) ProtoReflect() protoreflect.Message {
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Achievement.ProtoReflect.Descriptor instead.
func (*Achievement) Descriptor() ([]byte, []int) {
	return file_api_achievement_v1_achievement_proto_rawDescGZIP(), []int{0}
}

func (x *Achievement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Achievement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Achievement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Achievement) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *Achievement) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Achievement) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Achievement) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *Achievement) GetUnlockedAt() int64 {
	if x != nil {
		return x.UnlockedAt
	}
	return 0
}

func (x *Achievement) GetGemReward() int32 {
	if x != nil {
		return x.GemReward
	}
	return 0
}

type ListAchievementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAchievementsRequest) Reset() {
	*x = ListAchievementsRequest{}
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAchievementsRequest) ProtoMessage() {}

func (x *ListAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAchievementsRequest.ProtoReflect.Descriptor instead.
func (*ListAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_api_achievement_v1_achievement_proto_rawDescGZIP(), []int{1}
}

type ListAchievementsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievements  []*Achievement         `protobuf:"bytes,1,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAchievementsReply) Reset() {
	*x = ListAchievementsReply{}
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAchievementsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAchievementsReply) ProtoMessage() {}

func (x *ListAchievementsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAchievementsReply.ProtoReflect.Descriptor instead.
func (*ListAchievementsReply) Descriptor() ([]byte, []int) {
	return file_api_achievement_v1_achievement_proto_rawDescGZIP(), []int{2}
}

func (x *ListAchievementsReply) GetAchievements() []*Achievement {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_api_achievement_v1_achievement_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievement   *Achievement           `protobuf:"bytes,1,opt,name=achievement,proto3" json:"achievement,omitempty"`
	GemReward     int32                  `protobuf:"varint,2,opt,name=gem_reward,json=gemReward,proto3" json:"gem_reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockReply) Reset() {
	*x = UnlockReply{}
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockReply) ProtoMessage() {}

func (x *UnlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_achievement_v1_achievement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockReply.ProtoReflect.Descriptor instead.
func (*UnlockReply) Descriptor() ([]byte, []int) {
	return file_api_achievement_v1_achievement_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockReply) GetAchievement() *Achievement {
	if x != nil {
		return x.Achievement
	}
	return nil
}

func (x *UnlockReply) GetGemReward() int32 {
	if x != nil {
		return x.GemReward
	}
	return 0
}

var File_api_achievement_v1_achievement_proto protoreflect.FileDescriptor

const file_api_achievement_v1_achievement_proto_rawDesc = "" +
	"\n" +
	"$api/achievement/v1/achievement.proto\x12\x12api.achievement.v1\x1a\x1cgoogle/api/annotations.proto\"\x97\x02\n" +
	"\vAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0econdition_type\x18\x04 \x01(\tR\rconditionType\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12\x1f\n" +
	"\vis_unlocked\x18\a \x01(\bR\n" +
	"isUnlocked\x12\x1f\n" +
	"\vunlocked_at\x18\b \x01(\x03R\n" +
	"unlockedAt\x12\x1d\n" +
	"\n" +
	"gem_reward\x18\t \x01(\x05R\tgemReward\"\x19\n" +
	"\x17ListAchievementsRequest\"\\\n" +
	"\x15ListAchievementsReply\x12C\n" +
	"\fachievements\x18\x01 \x03(\v2\x1f.api.achievement.v1.AchievementR\fachievements\"\x1f\n" +
	"\rUnlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\vUnlockReply\x12A\n" +
	"\vachievement\x18\x01 \x01(\v2\x1f.api.achievement.v1.AchievementR\vachievement\x12\x1d\n" +
	"\n" +
	"gem_reward\x18\x02 \x01(\x05R\tgemReward2\x9a\x02\n" +
	"\x12AchievementService\x12\x88\x01\n" +
	"\x10ListAchievements\x12+.api.achievement.v1.ListAchievementsRequest\x1a).api.achievement.v1.ListAchievementsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/achievements\x12y\n" +
	"\x06Unlock\x12!.api.achievement.v1.UnlockRequest\x1a\x1f.api.achievement.v1.UnlockReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/achievements/{id}/unlockB5Z3github.com/habitforge/backend/api/achievement/v1;v1b\x06proto3"

var (
	file_api_achievement_v1_achievement_proto_rawDescOnce sync.Once
	file_api_achievement_v1_achievement_proto_rawDescData []byte
)

func file_api_achievement_v1_achievement_proto_rawDescGZIP() []byte {
	file_api_achievement_v1_achievement_proto_rawDescOnce.Do(func() {
		file_api_achievement_v1_achievement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_achievement_v1_achievement_proto_rawDesc), len(file_api_achievement_v1_achievement_proto_rawDesc)))
	})
	return file_api_achievement_v1_achievement_proto_rawDescData
}

var file_api_achievement_v1_achievement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_achievement_v1_achievement_proto_goTypes = []any{
	(*Achievement)(nil),             // 0: api.achievement.v1.Achievement
	(*ListAchievementsRequest)(nil), // 1: api.achievement.v1.ListAchievementsRequest
	(*ListAchievementsReply)(nil),   // 2: api.achievement.v1.ListAchievementsReply
	(*UnlockRequest)(nil),           // 3: api.achievement.v1.UnlockRequest
	(*UnlockReply)(nil),             // 4: api.achievement.v1.UnlockReply
}
var file_api_achievement_v1_achievement_proto_depIdxs = []int32{
	0, // 0: api.achievement.v1.ListAchievementsReply.achievements:type_name -> api.achievement.v1.Achievement
	0, // 1: api.achievement.v1.UnlockReply.achievement:type_name -> api.achievement.v1.Achievement
	1, // 2: api.achievement.v1.AchievementService.ListAchievements:input_type -> api.achievement.v1.ListAchievementsRequest
	3, // 3: api.achievement.v1.AchievementService.Unlock:input_type -> api.achievement.v1.UnlockRequest
	2, // 4: api.achievement.v1.AchievementService.ListAchievements:output_type -> api.achievement.v1.ListAchievementsReply
	4, // 5: api.achievement.v1.AchievementService.Unlock:output_type -> api.achievement.v1.UnlockReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_achievement_v1_achievement_proto_init() }
func file_api_achievement_v1_achievement_proto_init() {
	if File_api_achievement_v1_achievement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_achievement_v1_achievement_proto_rawDesc), len(file_api_achievement_v1_achievement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_achievement_v1_achievement_proto_goTypes,
		DependencyIndexes: file_api_achievement_v1_achievement_proto_depIdxs,
		MessageInfos:      file_api_achievement_v1_achievement_proto_msgTypes,
	}.Build()
	File_api_achievement_v1_achievement_proto = out.File
	file_api_achievement_v1_achievement_proto_goTypes = nil
	file_api_achievement_v1_achievement_proto_depIdxs = nil
}
