// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserServiceGetPrefs = "/api.user.v1.UserService/GetPrefs"
const OperationUserServiceUpdatePrefs = "/api.user.v1.UserService/UpdatePrefs"

type UserServiceHTTPServer interface {
	// GetPrefs GetPrefs returns the current user's preferences and wallet.
	GetPrefs(context.Context, *GetPrefsRequest) (*GetPrefsReply, error)
	// UpdatePrefs UpdatePrefs saves the current user's preferences and wallet.
	UpdatePrefs(context.Context, *UpdatePrefsRequest) (*UpdatePrefsReply, error)
}

func RegisterUserServiceHTTPServer(s *http.Server, srv UserServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/user/prefs", _UserService_GetPrefs0_HTTP_Handler(srv))
	r.PUT("/api/v1/user/prefs", _UserService_UpdatePrefs0_HTTP_Handler(srv))
}

func _UserService_GetPrefs0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPrefsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetPrefs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPrefs(ctx, req.(*GetPrefsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPrefsReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdatePrefs0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePrefsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdatePrefs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePrefs(ctx, req.(*UpdatePrefsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePrefsReply)
		return ctx.Result(200, reply)
	}
}

type UserServiceHTTPClient interface {
	// GetPrefs GetPrefs returns the current user's preferences and wallet.
	GetPrefs(ctx context.Context, req *GetPrefsRequest, opts ...http.CallOption) (rsp *GetPrefsReply, err error)
	// UpdatePrefs UpdatePrefs saves the current user's preferences and wallet.
	UpdatePrefs(ctx context.Context, req *UpdatePrefsRequest, opts ...http.CallOption) (rsp *UpdatePrefsReply, err error)
}

type UserServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserServiceHTTPClient(client *http.Client) UserServiceHTTPClient {
	return &UserServiceHTTPClientImpl{client}
}

// GetPrefs GetPrefs returns the current user's preferences and wallet.
func (c *UserServiceHTTPClientImpl) GetPrefs(ctx context.Context, in *GetPrefsRequest, opts ...http.CallOption) (*GetPrefsReply, error) {
	var out GetPrefsReply
	pattern := "/api/v1/user/prefs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserServiceGetPrefs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePrefs UpdatePrefs saves the current user's preferences and wallet.
func (c *UserServiceHTTPClientImpl) UpdatePrefs(ctx context.Context, in *UpdatePrefsRequest, opts ...http.CallOption) (*UpdatePrefsReply, error) {
	var out UpdatePrefsReply
	pattern := "/api/v1/user/prefs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceUpdatePrefs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
