// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserPrefs — per-user preferences, wallet balances and onboarding state.
type UserPrefs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the onboarding flow has been completed.
	OnboardingCompleted bool `protobuf:"varint,1,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	// Last onboarding step reached (used to resume the flow).
	LastOnboardingStep int32 `protobuf:"varint,2,opt,name=last_onboarding_step,json=lastOnboardingStep,proto3" json:"last_onboarding_step,omitempty"`
	// Current gold balance.
	CurrentGold int64 `protobuf:"varint,3,opt,name=current_gold,json=currentGold,proto3" json:"current_gold,omitempty"`
	// Current gem balance.
	CurrentGems int64 `protobuf:"varint,4,opt,name=current_gems,json=currentGems,proto3" json:"current_gems,omitempty"`
	// Whether sound effects are enabled.
	SoundEnabled bool `protobuf:"varint,5,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	// Whether haptic feedback is enabled.
	HapticEnabled bool `protobuf:"varint,6,opt,name=haptic_enabled,json=hapticEnabled,proto3" json:"haptic_enabled,omitempty"`
	// Whether push notifications are enabled.
	NotificationsEnabled bool `protobuf:"varint,7,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	// Lifetime count of completed tasks.
	TotalTasksCompleted int64 `protobuf:"varint,8,opt,name=total_tasks_completed,json=totalTasksCompleted,proto3" json:"total_tasks_completed,omitempty"`
	// Date of the first completed task, unix millis.
	FirstTaskDate int64 `protobuf:"varint,9,opt,name=first_task_date,json=firstTaskDate,proto3" json:"first_task_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPrefs) Reset() {
	*x = UserPrefs{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPrefs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrefs) ProtoMessage() {}

func (x *UserPrefs) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrefs.ProtoReflect.Descriptor instead.
func (*UserPrefs) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserPrefs) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *UserPrefs) GetLastOnboardingStep() int32 {
	if x != nil {
		return x.LastOnboardingStep
	}
	return 0
}

func (x *UserPrefs) GetCurrentGold() int64 {
	if x != nil {
		return x.CurrentGold
	}
	return 0
}

func (x *UserPrefs) GetCurrentGems() int64 {
	if x != nil {
		return x.CurrentGems
	}
	return 0
}

func (x *UserPrefs) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UserPrefs) GetHapticEnabled() bool {
	if x != nil {
		return x.HapticEnabled
	}
	return false
}

func (x *UserPrefs) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UserPrefs) GetTotalTasksCompleted() int64 {
	if x != nil {
		return x.TotalTasksCompleted
	}
	return 0
}

func (x *UserPrefs) GetFirstTaskDate() int64 {
	if x != nil {
		return x.FirstTaskDate
	}
	return 0
}

// GetPrefsRequest — no parameters.
type GetPrefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefsRequest) Reset() {
	*x = GetPrefsRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefsRequest) ProtoMessage() {}

func (x *GetPrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefsRequest.ProtoReflect.Descriptor instead.
func (*GetPrefsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

// GetPrefsReply — the current user's preferences.
type GetPrefsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's preferences and wallet.
	Prefs         *UserPrefs `protobuf:"bytes,1,opt,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefsReply) Reset() {
	*x = GetPrefsReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefsReply) ProtoMessage() {}

func (x *GetPrefsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefsReply.ProtoReflect.Descriptor instead.
func (*GetPrefsReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetPrefsReply) GetPrefs() *UserPrefs {
	if x != nil {
		return x.Prefs
	}
	return nil
}

// UpdatePrefsRequest — preferences to persist.
type UpdatePrefsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full preferences payload to save.
	Prefs         *UserPrefs `protobuf:"bytes,1,opt,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePrefsRequest) Reset() {
	*x = UpdatePrefsRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrefsRequest) ProtoMessage() {}

func (x *UpdatePrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrefsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePrefsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePrefsRequest) GetPrefs() *UserPrefs {
	if x != nil {
		return x.Prefs
	}
	return nil
}

// UpdatePrefsReply — the saved preferences.
type UpdatePrefsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The persisted preferences.
	Prefs         *UserPrefs `protobuf:"bytes,1,opt,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePrefsReply) Reset() {
	*x = UpdatePrefsReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrefsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrefsReply) ProtoMessage() {}

func (x *UpdatePrefsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrefsReply.ProtoReflect.Descriptor instead.
func (*UpdatePrefsReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePrefsReply) GetPrefs() *UserPrefs {
	if x != nil {
		return x.Prefs
	}
	return nil
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"\x93\x03\n" +
	"\tUserPrefs\x121\n" +
	"\x14onboarding_completed\x18\x01 \x01(\bR\x13onboardingCompleted\x120\n" +
	"\x14last_onboarding_step\x18\x02 \x01(\x05R\x12lastOnboardingStep\x12!\n" +
	"\fcurrent_gold\x18\x03 \x01(\x03R\vcurrentGold\x12!\n" +
	"\fcurrent_gems\x18\x04 \x01(\x03R\vcurrentGems\x12#\n" +
	"\rsound_enabled\x18\x05 \x01(\bR\fsoundEnabled\x12%\n" +
	"\x0ehaptic_enabled\x18\x06 \x01(\bR\rhapticEnabled\x123\n" +
	"\x15notifications_enabled\x18\a \x01(\bR\x14notificationsEnabled\x122\n" +
	"\x15total_tasks_completed\x18\b \x01(\x03R\x13totalTasksCompleted\x12&\n" +
	"\x0ffirst_task_date\x18\t \x01(\x03R\rfirstTaskDate\"\x11\n" +
	"\x0fGetPrefsRequest\"=\n" +
	"\rGetPrefsReply\x12,\n" +
	"\x05prefs\x18\x01 \x01(\v2\x16.api.user.v1.UserPrefsR\x05prefs\"B\n" +
	"\x12UpdatePrefsRequest\x12,\n" +
	"\x05prefs\x18\x01 \x01(\v2\x16.api.user.v1.UserPrefsR\x05prefs\"@\n" +
	"\x10UpdatePrefsReply\x12,\n" +
	"\x05prefs\x18\x01 \x01(\v2\x16.api.user.v1.UserPrefsR\x05prefs2\xdd\x01\n" +
	"\vUserService\x12`\n" +
	"\bGetPrefs\x12\x1c.api.user.v1.GetPrefsRequest\x1a\x1a.api.user.v1.GetPrefsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/user/prefs\x12l\n" +
	"\vUpdatePrefs\x12\x1f.api.user.v1.UpdatePrefsRequest\x1a\x1d.api.user.v1.UpdatePrefsReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/user/prefsB.Z,github.com/habitforge/backend/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_user_v1_user_proto_goTypes = []any{
	(*UserPrefs)(nil),          // 0: api.user.v1.UserPrefs
	(*GetPrefsRequest)(nil),    // 1: api.user.v1.GetPrefsRequest
	(*GetPrefsReply)(nil),      // 2: api.user.v1.GetPrefsReply
	(*UpdatePrefsRequest)(nil), // 3: api.user.v1.UpdatePrefsRequest
	(*UpdatePrefsReply)(nil),   // 4: api.user.v1.UpdatePrefsReply
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	0, // 0: api.user.v1.GetPrefsReply.prefs:type_name -> api.user.v1.UserPrefs
	0, // 1: api.user.v1.UpdatePrefsRequest.prefs:type_name -> api.user.v1.UserPrefs
	0, // 2: api.user.v1.UpdatePrefsReply.prefs:type_name -> api.user.v1.UserPrefs
	1, // 3: api.user.v1.UserService.GetPrefs:input_type -> api.user.v1.GetPrefsRequest
	3, // 4: api.user.v1.UserService.UpdatePrefs:input_type -> api.user.v1.UpdatePrefsRequest
	2, // 5: api.user.v1.UserService.GetPrefs:output_type -> api.user.v1.GetPrefsReply
	4, // 6: api.user.v1.UserService.UpdatePrefs:output_type -> api.user.v1.UpdatePrefsReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
