// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: stats/v1/stats.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatsRange — aggregation window.
type StatsRange int32

const (
	StatsRange_STATS_RANGE_UNSPECIFIED StatsRange = 0
	StatsRange_STATS_RANGE_DAY         StatsRange = 1
	StatsRange_STATS_RANGE_WEEK        StatsRange = 2
	StatsRange_STATS_RANGE_MONTH       StatsRange = 3
	StatsRange_STATS_RANGE_ALL         StatsRange = 4
)

// Enum value maps for StatsRange.
var (
	StatsRange_name = map[int32]string{
		0: "STATS_RANGE_UNSPECIFIED",
		1: "STATS_RANGE_DAY",
		2: "STATS_RANGE_WEEK",
		3: "STATS_RANGE_MONTH",
		4: "STATS_RANGE_ALL",
	}
	StatsRange_value = map[string]int32{
		"STATS_RANGE_UNSPECIFIED": 0,
		"STATS_RANGE_DAY":         1,
		"STATS_RANGE_WEEK":        2,
		"STATS_RANGE_MONTH":       3,
		"STATS_RANGE_ALL":         4,
	}
)

func (x StatsRange) Enum() *StatsRange {
	p := new(StatsRange)
	*p = x
	return p
}

func (x StatsRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatsRange) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_v1_stats_proto_enumTypes[0].Descriptor()
}

func (StatsRange) Type() protoreflect.EnumType {
	return &file_stats_v1_stats_proto_enumTypes[0]
}

func (x StatsRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatsRange.Descriptor instead.
func (StatsRange) EnumDescriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{0}
}

type TimeSegment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Label          string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // e.g. "Mon", "2026-08"
	CompletedCount int64                  `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSegment) Reset() {
	*x = TimeSegment{}
	mi := &file_stats_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSegment) ProtoMessage() {}

func (x *TimeSegment) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSegment.ProtoReflect.Descriptor instead.
func (*TimeSegment) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSegment) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimeSegment) GetCompletedCount() int64 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

type StreakEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Streak        int32                  `protobuf:"varint,3,opt,name=streak,proto3" json:"streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreakEntry) Reset() {
	*x = StreakEntry{}
	mi := &file_stats_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreakEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreakEntry) ProtoMessage() {}

func (x *StreakEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreakEntry.ProtoReflect.Descriptor instead.
func (*StreakEntry) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StreakEntry) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreakEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StreakEntry) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

type StatsReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Range               StatsRange             `protobuf:"varint,1,opt,name=range,proto3,enum=api.stats.v1.StatsRange" json:"range,omitempty"`
	Segments            []*TimeSegment         `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`                                            // completion bar chart data
	StreakLeaderboard   []*StreakEntry         `protobuf:"bytes,3,rep,name=streak_leaderboard,json=streakLeaderboard,proto3" json:"streak_leaderboard,omitempty"` // top streaks, desc
	TotalTasksCompleted int64                  `protobuf:"varint,4,opt,name=total_tasks_completed,json=totalTasksCompleted,proto3" json:"total_tasks_completed,omitempty"`
	TotalGoldEarned     int64                  `protobuf:"varint,5,opt,name=total_gold_earned,json=totalGoldEarned,proto3" json:"total_gold_earned,omitempty"`
	TotalExpEarned      int64                  `protobuf:"varint,6,opt,name=total_exp_earned,json=totalExpEarned,proto3" json:"total_exp_earned,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsReply) Reset() {
	*x = StatsReply{}
	mi := &file_stats_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReply) ProtoMessage() {}

func (x *StatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReply.ProtoReflect.Descriptor instead.
func (*StatsReply) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *StatsReply) GetRange() StatsRange {
	if x != nil {
		return x.Range
	}
	return StatsRange_STATS_RANGE_UNSPECIFIED
}

func (x *StatsReply) GetSegments() []*TimeSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *StatsReply) GetStreakLeaderboard() []*StreakEntry {
	if x != nil {
		return x.StreakLeaderboard
	}
	return nil
}

func (x *StatsReply) GetTotalTasksCompleted() int64 {
	if x != nil {
		return x.TotalTasksCompleted
	}
	return 0
}

func (x *StatsReply) GetTotalGoldEarned() int64 {
	if x != nil {
		return x.TotalGoldEarned
	}
	return 0
}

func (x *StatsReply) GetTotalExpEarned() int64 {
	if x != nil {
		return x.TotalExpEarned
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         StatsRange             `protobuf:"varint,1,opt,name=range,proto3,enum=api.stats.v1.StatsRange" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatsRequest) GetRange() StatsRange {
	if x != nil {
		return x.Range
	}
	return StatsRange_STATS_RANGE_UNSPECIFIED
}

type GetStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *StatsReply            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReply) Reset() {
	*x = GetStatsReply{}
	mi := &file_stats_v1_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReply) ProtoMessage() {}

func (x *GetStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReply.ProtoReflect.Descriptor instead.
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsReply) GetStats() *StatsReply {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_stats_v1_stats_proto protoreflect.FileDescriptor

const file_stats_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x14stats/v1/stats.proto\x12\fapi.stats.v1\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\vTimeSegment\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12'\n" +
	"\x0fcompleted_count\x18\x02 \x01(\x03R\x0ecompletedCount\"T\n" +
	"\vStreakEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06streak\x18\x03 \x01(\x05R\x06streak\"\xc7\x02\n" +
	"\n" +
	"StatsReply\x12.\n" +
	"\x05range\x18\x01 \x01(\x0e2\x18.api.stats.v1.StatsRangeR\x05range\x125\n" +
	"\bsegments\x18\x02 \x03(\v2\x19.api.stats.v1.TimeSegmentR\bsegments\x12H\n" +
	"\x12streak_leaderboard\x18\x03 \x03(\v2\x19.api.stats.v1.StreakEntryR\x11streakLeaderboard\x122\n" +
	"\x15total_tasks_completed\x18\x04 \x01(\x03R\x13totalTasksCompleted\x12*\n" +
	"\x11total_gold_earned\x18\x05 \x01(\x03R\x0ftotalGoldEarned\x12(\n" +
	"\x10total_exp_earned\x18\x06 \x01(\x03R\x0etotalExpEarned\"A\n" +
	"\x0fGetStatsRequest\x12.\n" +
	"\x05range\x18\x01 \x01(\x0e2\x18.api.stats.v1.StatsRangeR\x05range\"?\n" +
	"\rGetStatsReply\x12.\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.api.stats.v1.StatsReplyR\x05stats*\x80\x01\n" +
	"\n" +
	"StatsRange\x12\x1b\n" +
	"\x17STATS_RANGE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATS_RANGE_DAY\x10\x01\x12\x14\n" +
	"\x10STATS_RANGE_WEEK\x10\x02\x12\x15\n" +
	"\x11STATS_RANGE_MONTH\x10\x03\x12\x13\n" +
	"\x0fSTATS_RANGE_ALL\x10\x042m\n" +
	"\fStatsService\x12]\n" +
	"\bGetStats\x12\x1d.api.stats.v1.GetStatsRequest\x1a\x1b.api.stats.v1.GetStatsReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/statsB/Z-github.com/habitforge/backend/api/stats/v1;v1b\x06proto3"

var (
	file_stats_v1_stats_proto_rawDescOnce sync.Once
	file_stats_v1_stats_proto_rawDescData []byte
)

func file_stats_v1_stats_proto_rawDescGZIP() []byte {
	file_stats_v1_stats_proto_rawDescOnce.Do(func() {
		file_stats_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_v1_stats_proto_rawDesc), len(file_stats_v1_stats_proto_rawDesc)))
	})
	return file_stats_v1_stats_proto_rawDescData
}

var file_stats_v1_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stats_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stats_v1_stats_proto_goTypes = []any{
	(StatsRange)(0),         // 0: api.stats.v1.StatsRange
	(*TimeSegment)(nil),     // 1: api.stats.v1.TimeSegment
	(*StreakEntry)(nil),     // 2: api.stats.v1.StreakEntry
	(*StatsReply)(nil),      // 3: api.stats.v1.StatsReply
	(*GetStatsRequest)(nil), // 4: api.stats.v1.GetStatsRequest
	(*GetStatsReply)(nil),   // 5: api.stats.v1.GetStatsReply
}
var file_stats_v1_stats_proto_depIdxs = []int32{
	0, // 0: api.stats.v1.StatsReply.range:type_name -> api.stats.v1.StatsRange
	1, // 1: api.stats.v1.StatsReply.segments:type_name -> api.stats.v1.TimeSegment
	2, // 2: api.stats.v1.StatsReply.streak_leaderboard:type_name -> api.stats.v1.StreakEntry
	0, // 3: api.stats.v1.GetStatsRequest.range:type_name -> api.stats.v1.StatsRange
	3, // 4: api.stats.v1.GetStatsReply.stats:type_name -> api.stats.v1.StatsReply
	4, // 5: api.stats.v1.StatsService.GetStats:input_type -> api.stats.v1.GetStatsRequest
	5, // 6: api.stats.v1.StatsService.GetStats:output_type -> api.stats.v1.GetStatsReply
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stats_v1_stats_proto_init() }
func file_stats_v1_stats_proto_init() {
	if File_stats_v1_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_v1_stats_proto_rawDesc), len(file_stats_v1_stats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_v1_stats_proto_goTypes,
		DependencyIndexes: file_stats_v1_stats_proto_depIdxs,
		EnumInfos:         file_stats_v1_stats_proto_enumTypes,
		MessageInfos:      file_stats_v1_stats_proto_msgTypes,
	}.Build()
	File_stats_v1_stats_proto = out.File
	file_stats_v1_stats_proto_goTypes = nil
	file_stats_v1_stats_proto_depIdxs = nil
}
