// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: stats/v1/stats.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStatsServiceGetStats = "/api.stats.v1.StatsService/GetStats"

type StatsServiceHTTPServer interface {
	// GetStats GetStats returns task statistics over a time range.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsReply, error)
}

func RegisterStatsServiceHTTPServer(s *http.Server, srv StatsServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/stats", _StatsService_GetStats0_HTTP_Handler(srv))
}

func _StatsService_GetStats0_HTTP_Handler(srv StatsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStatsServiceGetStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStats(ctx, req.(*GetStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStatsReply)
		return ctx.Result(200, reply)
	}
}

type StatsServiceHTTPClient interface {
	// GetStats GetStats returns task statistics over a time range.
	GetStats(ctx context.Context, req *GetStatsRequest, opts ...http.CallOption) (rsp *GetStatsReply, err error)
}

type StatsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStatsServiceHTTPClient(client *http.Client) StatsServiceHTTPClient {
	return &StatsServiceHTTPClientImpl{client}
}

// GetStats GetStats returns task statistics over a time range.
func (c *StatsServiceHTTPClientImpl) GetStats(ctx context.Context, in *GetStatsRequest, opts ...http.CallOption) (*GetStatsReply, error) {
	var out GetStatsReply
	pattern := "/api/v1/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStatsServiceGetStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
