// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/shared/v1/shared.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SysMaterial — in-game currency types shown in the wallet.
type SysMaterial int32

const (
	// Gold — earned by completing tasks.
	SysMaterial_SYSMATERIAL_GOLD SysMaterial = 0
	// Gem — earned by completing achievements.
	SysMaterial_SYSMATERIAL_GEM SysMaterial = 1
	// Exp — earned by completing tasks, can be spent on character upgrades.
	SysMaterial_SYSMATERIAL_EXP SysMaterial = 2
)

// Enum value maps for SysMaterial.
var (
	SysMaterial_name = map[int32]string{
		0: "SYSMATERIAL_GOLD",
		1: "SYSMATERIAL_GEM",
		2: "SYSMATERIAL_EXP",
	}
	SysMaterial_value = map[string]int32{
		"SYSMATERIAL_GOLD": 0,
		"SYSMATERIAL_GEM":  1,
		"SYSMATERIAL_EXP":  2,
	}
)

func (x SysMaterial) Enum() *SysMaterial {
	p := new(SysMaterial)
	*p = x
	return p
}

func (x SysMaterial) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SysMaterial) Descriptor() protoreflect.EnumDescriptor {
	return file_api_shared_v1_shared_proto_enumTypes[0].Descriptor()
}

func (SysMaterial) Type() protoreflect.EnumType {
	return &file_api_shared_v1_shared_proto_enumTypes[0]
}

func (x SysMaterial) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SysMaterial.Descriptor instead.
func (SysMaterial) EnumDescriptor() ([]byte, []int) {
	return file_api_shared_v1_shared_proto_rawDescGZIP(), []int{0}
}

// EquipmentSlot — equipment slots a shop item can occupy.
type EquipmentSlot int32

const (
	// Unspecified slot; used as the zero value.
	EquipmentSlot_EQUIPMENT_SLOT_UNSPECIFIED EquipmentSlot = 0
	// Weapon slot.
	EquipmentSlot_EQUIPMENT_SLOT_WEAPON EquipmentSlot = 1
	// Helmet slot.
	EquipmentSlot_EQUIPMENT_SLOT_HELMET EquipmentSlot = 2
	// Armor slot.
	EquipmentSlot_EQUIPMENT_SLOT_ARMOR EquipmentSlot = 3
	// Accessory slot.
	EquipmentSlot_EQUIPMENT_SLOT_ACCESSORY EquipmentSlot = 4
)

// Enum value maps for EquipmentSlot.
var (
	EquipmentSlot_name = map[int32]string{
		0: "EQUIPMENT_SLOT_UNSPECIFIED",
		1: "EQUIPMENT_SLOT_WEAPON",
		2: "EQUIPMENT_SLOT_HELMET",
		3: "EQUIPMENT_SLOT_ARMOR",
		4: "EQUIPMENT_SLOT_ACCESSORY",
	}
	EquipmentSlot_value = map[string]int32{
		"EQUIPMENT_SLOT_UNSPECIFIED": 0,
		"EQUIPMENT_SLOT_WEAPON":      1,
		"EQUIPMENT_SLOT_HELMET":      2,
		"EQUIPMENT_SLOT_ARMOR":       3,
		"EQUIPMENT_SLOT_ACCESSORY":   4,
	}
)

func (x EquipmentSlot) Enum() *EquipmentSlot {
	p := new(EquipmentSlot)
	*p = x
	return p
}

func (x EquipmentSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EquipmentSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_api_shared_v1_shared_proto_enumTypes[1].Descriptor()
}

func (EquipmentSlot) Type() protoreflect.EnumType {
	return &file_api_shared_v1_shared_proto_enumTypes[1]
}

func (x EquipmentSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EquipmentSlot.Descriptor instead.
func (EquipmentSlot) EnumDescriptor() ([]byte, []int) {
	return file_api_shared_v1_shared_proto_rawDescGZIP(), []int{1}
}

var File_api_shared_v1_shared_proto protoreflect.FileDescriptor

const file_api_shared_v1_shared_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/shared/v1/shared.proto\x12\rapi.shared.v1*M\n" +
	"\vSysMaterial\x12\x14\n" +
	"\x10SYSMATERIAL_GOLD\x10\x00\x12\x13\n" +
	"\x0fSYSMATERIAL_GEM\x10\x01\x12\x13\n" +
	"\x0fSYSMATERIAL_EXP\x10\x02*\x9d\x01\n" +
	"\rEquipmentSlot\x12\x1e\n" +
	"\x1aEQUIPMENT_SLOT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EQUIPMENT_SLOT_WEAPON\x10\x01\x12\x19\n" +
	"\x15EQUIPMENT_SLOT_HELMET\x10\x02\x12\x18\n" +
	"\x14EQUIPMENT_SLOT_ARMOR\x10\x03\x12\x1c\n" +
	"\x18EQUIPMENT_SLOT_ACCESSORY\x10\x04B0Z.github.com/habitforge/backend/api/shared/v1;v1b\x06proto3"

var (
	file_api_shared_v1_shared_proto_rawDescOnce sync.Once
	file_api_shared_v1_shared_proto_rawDescData []byte
)

func file_api_shared_v1_shared_proto_rawDescGZIP() []byte {
	file_api_shared_v1_shared_proto_rawDescOnce.Do(func() {
		file_api_shared_v1_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shared_v1_shared_proto_rawDesc), len(file_api_shared_v1_shared_proto_rawDesc)))
	})
	return file_api_shared_v1_shared_proto_rawDescData
}

var file_api_shared_v1_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_shared_v1_shared_proto_goTypes = []any{
	(SysMaterial)(0),   // 0: api.shared.v1.SysMaterial
	(EquipmentSlot)(0), // 1: api.shared.v1.EquipmentSlot
}
var file_api_shared_v1_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_shared_v1_shared_proto_init() }
func file_api_shared_v1_shared_proto_init() {
	if File_api_shared_v1_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shared_v1_shared_proto_rawDesc), len(file_api_shared_v1_shared_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_shared_v1_shared_proto_goTypes,
		DependencyIndexes: file_api_shared_v1_shared_proto_depIdxs,
		EnumInfos:         file_api_shared_v1_shared_proto_enumTypes,
	}.Build()
	File_api_shared_v1_shared_proto = out.File
	file_api_shared_v1_shared_proto_goTypes = nil
	file_api_shared_v1_shared_proto_depIdxs = nil
}
