// Code generated by Wire (hand-maintained until the wire tool is run).
//go:generate go run -mod=mod github.com/google/wire/cmd/wire

//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/habitforge/backend/internal/biz"
	"github.com/habitforge/backend/internal/conf"
	"github.com/habitforge/backend/internal/server"
	"github.com/habitforge/backend/internal/service"
)

// wireApp wires the whole application.
func wireApp(cfg *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	authUseCase := biz.NewAuthUseCase()
	userUseCase := biz.NewUserUseCase()
	characterUseCase := biz.NewCharacterUseCase()
	taskUseCase := biz.NewTaskUseCase()
	shopUseCase := biz.NewShopUseCase()
	achievementUseCase := biz.NewAchievementUseCase()
	statsUseCase := biz.NewStatsUseCase()

	authService := service.NewAuthService(authUseCase)
	userService := service.NewUserService(userUseCase)
	characterService := service.NewCharacterService(characterUseCase)
	taskService := service.NewTaskService(taskUseCase)
	shopService := service.NewShopService(shopUseCase)
	achievementService := service.NewAchievementService(achievementUseCase)
	statsService := service.NewStatsService(statsUseCase)

	httpServer := server.NewHTTPServer(cfg.Server, cfg.JWT, logger,
		authService, userService, characterService, taskService, shopService, achievementService, statsService)
	grpcServer := server.NewGRPCServer(cfg.Server, logger,
		authService, userService, characterService, taskService, shopService, achievementService, statsService)

	app := newApp(logger, httpServer, grpcServer)
	return app, func() {}, nil
}
