// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/habitforge/backend/api"
	"github.com/habitforge/backend/config"
	"github.com/habitforge/backend/internal/handler"
	"github.com/habitforge/backend/internal/repository"
	"github.com/habitforge/backend/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, cfg *config.Config) *api.Router {
	userRepository := repository.NewUserRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	authService := service.NewAuthService(userRepository, jwtConfig)
	authHandler := handler.NewAuthHandler(authService)
	router := api.NewRouter(authHandler, authService)
	return router
}

// wire.go:

func provideJWTConfig(cfg *config.Config) config.JWTConfig {
	return cfg.JWT
}
