// Emits the ledger fixtures the emulator rules test feeds into Firestore.
//
// Why a generator instead of hand-written JSON: the Firestore rules mirror the
// caps and the payload shape in `lib/core/network/ledger/ledger_event.dart`, and
// a client row the rules reject would abort the whole atomic write — i.e. it
// would break a real game action. These fixtures are built by the *same*
// factories the Firebase impl uses, so `firebase/test/firestore.rules.test.mjs`
// proves "what Dart writes is what the rules accept".
// `test/ledger_fixtures_test.dart` fails when the committed file drifts.
//
// Usage (from `app/`):
//   dart run tool/emit_ledger_fixtures.dart [--out firebase/test/fixtures/ledger_events.json]

import 'dart:convert';
import 'dart:io';

import 'package:habit_forge_app/core/network/ledger/game_ledger.dart';
import 'package:habit_forge_app/core/network/ledger/ledger_event.dart';
import 'package:habit_forge_app/generated/protos/achievement/v1/achievement.pb.dart';
import 'package:habit_forge_app/generated/protos/character/v1/character.pb.dart';
import 'package:habit_forge_app/generated/protos/shop/v1/shop.pb.dart';
import 'package:habit_forge_app/generated/protos/task/v1/task.pb.dart';
import 'package:habit_forge_app/generated/protos/user/v1/user.pb.dart';
import 'package:fixnum/fixnum.dart';

/// Path of the committed fixture file, relative to `app/`.
const String defaultFixturePath = 'firebase/test/fixtures/ledger_events.json';

Future<void> main(List<String> args) async {
  var out = defaultFixturePath;
  for (var i = 0; i < args.length; i++) {
    if (args[i] == '--out' && i + 1 < args.length) out = args[++i];
  }
  final file = File(out);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(encodeLedgerFixtures());
  stdout.writeln('wrote ${buildLedgerFixtures().length} fixture rows to $out');
}

/// Encoded fixture document, exactly as committed.
String encodeLedgerFixtures() {
  const encoder = JsonEncoder.withIndent('  ');
  return '${encoder.convert(<String, Object?>{'comment': _comment, 'events': buildLedgerFixtures()})}\n';
}

const String _comment =
    'GENERATED by `dart run tool/emit_ledger_fixtures.dart` — do not edit by hand. '
    'One row per LedgerEventType, built by GameLedger so the emulator rules test '
    'checks exactly what the app writes.';

/// One realistic row per event type, ready to POST to the emulator.
///
/// Values are the *shape* that matters (field names, types, magnitudes); the
/// timestamps are fixed so the file is reproducible.
List<Map<String, Object?>> buildLedgerFixtures() {
  const uid = 'fixture-uid';
  final now = DateTime.utc(2026, 9, 29, 8, 30);
  final at = now.millisecondsSinceEpoch;

  final task = Task()
    ..id = 'task-fixture-1'
    ..title = 'Read 30 minutes'
    ..type = TaskType.TASK_TYPE_HABIT
    ..difficulty = TaskDifficulty.TASK_DIFFICULTY_MEDIUM
    ..streak = 12;
  final negativeHabit = Task()
    ..id = 'task-fixture-2'
    ..title = 'No late-night scrolling'
    ..type = TaskType.TASK_TYPE_HABIT
    ..difficulty = TaskDifficulty.TASK_DIFFICULTY_MEDIUM
    ..hpPenalty = 10
    ..isNegative = true;
  final character = Character()
    ..id = 'char-fixture-1'
    ..level = 4
    ..currentExp = Int64(37)
    ..currentHp = 82;
  final prefs = UserPrefs()
    ..currentGold = Int64(640)
    ..currentGems = Int64(25)
    ..totalTasksCompleted = Int64(51);
  final achievement = Achievement()
    ..id = 'streak_7'
    ..conditionType = 'streak'
    ..threshold = 7
    ..gemReward = 5;

  final rows = <LedgerEvent>[
    GameLedger.openingBalance(prefs: prefs, character: character, now: now, ledgerStartedAt: at),
    GameLedger.taskCompleted(task: task, exp: 33, gold: 11, hpDelta: 20, now: now, leveledTo: 4),
    GameLedger.habitSlipped(task: negativeHabit, hpDelta: -10, now: now),
    GameLedger.dailyPenalty(uid: uid, hpDelta: -30, now: now),
    GameLedger.revive(character: character, hpDelta: 50, deathRecoveryUntilMs: at - 60000, now: now),
    GameLedger.purchase(
      itemId: 'sword_flame',
      currency: ShopCurrency.SHOP_CURRENCY_GOLD,
      price: 350,
      discountPercent: 30,
      now: now,
    ),
    GameLedger.statAllocated(uid: uid, stat: StatType.STAT_TYPE_STRENGTH, pointsBefore: 3, now: now),
    GameLedger.achievementUnlocked(achievement: achievement, now: now),
  ];

  for (final row in rows) {
    final reason = row.validate();
    if (reason != null) {
      throw StateError('fixture ${row.eventId} would be rejected by the client: $reason');
    }
  }
  return rows.map((row) => row.toMap()).toList();
}
