// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/shop/v1/shop.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShopCurrency — purchase currency.
type ShopCurrency int32

const (
	ShopCurrency_SHOP_CURRENCY_UNSPECIFIED ShopCurrency = 0
	ShopCurrency_SHOP_CURRENCY_GOLD        ShopCurrency = 1
	ShopCurrency_SHOP_CURRENCY_GEMS        ShopCurrency = 2
)

// Enum value maps for ShopCurrency.
var (
	ShopCurrency_name = map[int32]string{
		0: "SHOP_CURRENCY_UNSPECIFIED",
		1: "SHOP_CURRENCY_GOLD",
		2: "SHOP_CURRENCY_GEMS",
	}
	ShopCurrency_value = map[string]int32{
		"SHOP_CURRENCY_UNSPECIFIED": 0,
		"SHOP_CURRENCY_GOLD":        1,
		"SHOP_CURRENCY_GEMS":        2,
	}
)

func (x ShopCurrency) Enum() *ShopCurrency {
	p := new(ShopCurrency)
	*p = x
	return p
}

func (x ShopCurrency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopCurrency) Descriptor() protoreflect.EnumDescriptor {
	return file_api_shop_v1_shop_proto_enumTypes[0].Descriptor()
}

func (ShopCurrency) Type() protoreflect.EnumType {
	return &file_api_shop_v1_shop_proto_enumTypes[0]
}

func (x ShopCurrency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopCurrency.Descriptor instead.
func (ShopCurrency) EnumDescriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // e.g. "weapon" | "helmet" | "armor" | "accessory"
	Rarity        string                 `protobuf:"bytes,6,opt,name=rarity,proto3" json:"rarity,omitempty"`     // e.g. "common" | "rare" | "epic" | "legendary"
	GlbAssetPath  string                 `protobuf:"bytes,7,opt,name=glb_asset_path,json=glbAssetPath,proto3" json:"glb_asset_path,omitempty"`
	IsOwned       bool                   `protobuf:"varint,8,opt,name=is_owned,json=isOwned,proto3" json:"is_owned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShopItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ShopItem) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *ShopItem) GetGlbAssetPath() string {
	if x != nil {
		return x.GlbAssetPath
	}
	return ""
}

func (x *ShopItem) GetIsOwned() bool {
	if x != nil {
		return x.IsOwned
	}
	return false
}

type DailyDeal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemId          string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DiscountPercent int32                  `protobuf:"varint,2,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix millis
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyDeal) Reset() {
	*x = DailyDeal{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyDeal) ProtoMessage() {}

func (x *DailyDeal) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyDeal.ProtoReflect.Descriptor instead.
func (*DailyDeal) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *DailyDeal) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DailyDeal) GetDiscountPercent() int32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *DailyDeal) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ListShopItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopItemsRequest) Reset() {
	*x = ListShopItemsRequest{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopItemsRequest) ProtoMessage() {}

func (x *ListShopItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopItemsRequest.ProtoReflect.Descriptor instead.
func (*ListShopItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *ListShopItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListShopItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShopItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopItemsReply) Reset() {
	*x = ListShopItemsReply{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopItemsReply) ProtoMessage() {}

func (x *ListShopItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopItemsReply.ProtoReflect.Descriptor instead.
func (*ListShopItemsReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *ListShopItemsReply) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetDailyDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyDealRequest) Reset() {
	*x = GetDailyDealRequest{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyDealRequest) ProtoMessage() {}

func (x *GetDailyDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyDealRequest.ProtoReflect.Descriptor instead.
func (*GetDailyDealRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

type GetDailyDealReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deal          *DailyDeal             `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyDealReply) Reset() {
	*x = GetDailyDealReply{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyDealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyDealReply) ProtoMessage() {}

func (x *GetDailyDealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyDealReply.ProtoReflect.Descriptor instead.
func (*GetDailyDealReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{5}
}

func (x *GetDailyDealReply) GetDeal() *DailyDeal {
	if x != nil {
		return x.Deal
	}
	return nil
}

type BuyItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Currency      ShopCurrency           `protobuf:"varint,2,opt,name=currency,proto3,enum=api.shop.v1.ShopCurrency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemRequest) Reset() {
	*x = BuyItemRequest{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemRequest) ProtoMessage() {}

func (x *BuyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemRequest.ProtoReflect.Descriptor instead.
func (*BuyItemRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{6}
}

func (x *BuyItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BuyItemRequest) GetCurrency() ShopCurrency {
	if x != nil {
		return x.Currency
	}
	return ShopCurrency_SHOP_CURRENCY_UNSPECIFIED
}

type BuyItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ShopItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"` // remaining balance of the spent currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemReply) Reset() {
	*x = BuyItemReply{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemReply) ProtoMessage() {}

func (x *BuyItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemReply.ProtoReflect.Descriptor instead.
func (*BuyItemReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{7}
}

func (x *BuyItemReply) GetItem() *ShopItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *BuyItemReply) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ListOwnedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedItemsRequest) Reset() {
	*x = ListOwnedItemsRequest{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedItemsRequest) ProtoMessage() {}

func (x *ListOwnedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnedItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{8}
}

type ListOwnedItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedItemsReply) Reset() {
	*x = ListOwnedItemsReply{}
	mi := &file_api_shop_v1_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedItemsReply) ProtoMessage() {}

func (x *ListOwnedItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedItemsReply.ProtoReflect.Descriptor instead.
func (*ListOwnedItemsReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_shop_proto_rawDescGZIP(), []int{9}
}

func (x *ListOwnedItemsReply) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

var File_api_shop_v1_shop_proto protoreflect.FileDescriptor

const file_api_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x16api/shop/v1/shop.proto\x12\vapi.shop.v1\x1a\x1cgoogle/api/annotations.proto\"\xdb\x01\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06rarity\x18\x06 \x01(\tR\x06rarity\x12$\n" +
	"\x0eglb_asset_path\x18\a \x01(\tR\fglbAssetPath\x12\x19\n" +
	"\bis_owned\x18\b \x01(\bR\aisOwned\"n\n" +
	"\tDailyDeal\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12)\n" +
	"\x10discount_percent\x18\x02 \x01(\x05R\x0fdiscountPercent\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"2\n" +
	"\x14ListShopItemsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"A\n" +
	"\x12ListShopItemsReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api.shop.v1.ShopItemR\x05items\"\x15\n" +
	"\x13GetDailyDealRequest\"?\n" +
	"\x11GetDailyDealReply\x12*\n" +
	"\x04deal\x18\x01 \x01(\v2\x16.api.shop.v1.DailyDealR\x04deal\"`\n" +
	"\x0eBuyItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x125\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x19.api.shop.v1.ShopCurrencyR\bcurrency\"S\n" +
	"\fBuyItemReply\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.api.shop.v1.ShopItemR\x04item\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"\x17\n" +
	"\x15ListOwnedItemsRequest\"0\n" +
	"\x13ListOwnedItemsReply\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds*]\n" +
	"\fShopCurrency\x12\x1d\n" +
	"\x19SHOP_CURRENCY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SHOP_CURRENCY_GOLD\x10\x01\x12\x16\n" +
	"\x12SHOP_CURRENCY_GEMS\x10\x022\xd5\x03\n" +
	"\vShopService\x12o\n" +
	"\rListShopItems\x12!.api.shop.v1.ListShopItemsRequest\x1a\x1f.api.shop.v1.ListShopItemsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/shop/items\x12q\n" +
	"\fGetDailyDeal\x12 .api.shop.v1.GetDailyDealRequest\x1a\x1e.api.shop.v1.GetDailyDealReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/shop/daily-deal\x12n\n" +
	"\aBuyItem\x12\x1b.api.shop.v1.BuyItemRequest\x1a\x19.api.shop.v1.BuyItemReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/shop/items/{item_id}/buy\x12r\n" +
	"\x0eListOwnedItems\x12\".api.shop.v1.ListOwnedItemsRequest\x1a .api.shop.v1.ListOwnedItemsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/shop/ownedB.Z,github.com/habitforge/backend/api/shop/v1;v1b\x06proto3"

var (
	file_api_shop_v1_shop_proto_rawDescOnce sync.Once
	file_api_shop_v1_shop_proto_rawDescData []byte
)

func file_api_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_api_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_api_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shop_v1_shop_proto_rawDesc), len(file_api_shop_v1_shop_proto_rawDesc)))
	})
	return file_api_shop_v1_shop_proto_rawDescData
}

var file_api_shop_v1_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_shop_v1_shop_proto_goTypes = []any{
	(ShopCurrency)(0),             // 0: api.shop.v1.ShopCurrency
	(*ShopItem)(nil),              // 1: api.shop.v1.ShopItem
	(*DailyDeal)(nil),             // 2: api.shop.v1.DailyDeal
	(*ListShopItemsRequest)(nil),  // 3: api.shop.v1.ListShopItemsRequest
	(*ListShopItemsReply)(nil),    // 4: api.shop.v1.ListShopItemsReply
	(*GetDailyDealRequest)(nil),   // 5: api.shop.v1.GetDailyDealRequest
	(*GetDailyDealReply)(nil),     // 6: api.shop.v1.GetDailyDealReply
	(*BuyItemRequest)(nil),        // 7: api.shop.v1.BuyItemRequest
	(*BuyItemReply)(nil),          // 8: api.shop.v1.BuyItemReply
	(*ListOwnedItemsRequest)(nil), // 9: api.shop.v1.ListOwnedItemsRequest
	(*ListOwnedItemsReply)(nil),   // 10: api.shop.v1.ListOwnedItemsReply
}
var file_api_shop_v1_shop_proto_depIdxs = []int32{
	1,  // 0: api.shop.v1.ListShopItemsReply.items:type_name -> api.shop.v1.ShopItem
	2,  // 1: api.shop.v1.GetDailyDealReply.deal:type_name -> api.shop.v1.DailyDeal
	0,  // 2: api.shop.v1.BuyItemRequest.currency:type_name -> api.shop.v1.ShopCurrency
	1,  // 3: api.shop.v1.BuyItemReply.item:type_name -> api.shop.v1.ShopItem
	3,  // 4: api.shop.v1.ShopService.ListShopItems:input_type -> api.shop.v1.ListShopItemsRequest
	5,  // 5: api.shop.v1.ShopService.GetDailyDeal:input_type -> api.shop.v1.GetDailyDealRequest
	7,  // 6: api.shop.v1.ShopService.BuyItem:input_type -> api.shop.v1.BuyItemRequest
	9,  // 7: api.shop.v1.ShopService.ListOwnedItems:input_type -> api.shop.v1.ListOwnedItemsRequest
	4,  // 8: api.shop.v1.ShopService.ListShopItems:output_type -> api.shop.v1.ListShopItemsReply
	6,  // 9: api.shop.v1.ShopService.GetDailyDeal:output_type -> api.shop.v1.GetDailyDealReply
	8,  // 10: api.shop.v1.ShopService.BuyItem:output_type -> api.shop.v1.BuyItemReply
	10, // 11: api.shop.v1.ShopService.ListOwnedItems:output_type -> api.shop.v1.ListOwnedItemsReply
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_shop_v1_shop_proto_init() }
func file_api_shop_v1_shop_proto_init() {
	if File_api_shop_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shop_v1_shop_proto_rawDesc), len(file_api_shop_v1_shop_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_api_shop_v1_shop_proto_depIdxs,
		EnumInfos:         file_api_shop_v1_shop_proto_enumTypes,
		MessageInfos:      file_api_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_api_shop_v1_shop_proto = out.File
	file_api_shop_v1_shop_proto_goTypes = nil
	file_api_shop_v1_shop_proto_depIdxs = nil
}
