// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shop/v1/shop.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopService_ListShopItems_FullMethodName  = "/api.shop.v1.ShopService/ListShopItems"
	ShopService_GetDailyDeal_FullMethodName   = "/api.shop.v1.ShopService/GetDailyDeal"
	ShopService_BuyItem_FullMethodName        = "/api.shop.v1.ShopService/BuyItem"
	ShopService_ListOwnedItems_FullMethodName = "/api.shop.v1.ShopService/ListOwnedItems"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShopService — Forge shop: items, daily deals, purchases, owned items.
type ShopServiceClient interface {
	// ListShopItems lists all purchasable shop items.
	ListShopItems(ctx context.Context, in *ListShopItemsRequest, opts ...grpc.CallOption) (*ListShopItemsReply, error)
	// GetDailyDeal returns the current rotating discounted item.
	GetDailyDeal(ctx context.Context, in *GetDailyDealRequest, opts ...grpc.CallOption) (*GetDailyDealReply, error)
	// BuyItem purchases an item with gold or gems.
	BuyItem(ctx context.Context, in *BuyItemRequest, opts ...grpc.CallOption) (*BuyItemReply, error)
	// ListOwnedItems lists items the current user owns.
	ListOwnedItems(ctx context.Context, in *ListOwnedItemsRequest, opts ...grpc.CallOption) (*ListOwnedItemsReply, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) ListShopItems(ctx context.Context, in *ListShopItemsRequest, opts ...grpc.CallOption) (*ListShopItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopItemsReply)
	err := c.cc.Invoke(ctx, ShopService_ListShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetDailyDeal(ctx context.Context, in *GetDailyDealRequest, opts ...grpc.CallOption) (*GetDailyDealReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyDealReply)
	err := c.cc.Invoke(ctx, ShopService_GetDailyDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) BuyItem(ctx context.Context, in *BuyItemRequest, opts ...grpc.CallOption) (*BuyItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyItemReply)
	err := c.cc.Invoke(ctx, ShopService_BuyItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListOwnedItems(ctx context.Context, in *ListOwnedItemsRequest, opts ...grpc.CallOption) (*ListOwnedItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOwnedItemsReply)
	err := c.cc.Invoke(ctx, ShopService_ListOwnedItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility.
//
// ShopService — Forge shop: items, daily deals, purchases, owned items.
type ShopServiceServer interface {
	// ListShopItems lists all purchasable shop items.
	ListShopItems(context.Context, *ListShopItemsRequest) (*ListShopItemsReply, error)
	// GetDailyDeal returns the current rotating discounted item.
	GetDailyDeal(context.Context, *GetDailyDealRequest) (*GetDailyDealReply, error)
	// BuyItem purchases an item with gold or gems.
	BuyItem(context.Context, *BuyItemRequest) (*BuyItemReply, error)
	// ListOwnedItems lists items the current user owns.
	ListOwnedItems(context.Context, *ListOwnedItemsRequest) (*ListOwnedItemsReply, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServiceServer struct{}

func (UnimplementedShopServiceServer) ListShopItems(context.Context, *ListShopItemsRequest) (*ListShopItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopItems not implemented")
}
func (UnimplementedShopServiceServer) GetDailyDeal(context.Context, *GetDailyDealRequest) (*GetDailyDealReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyDeal not implemented")
}
func (UnimplementedShopServiceServer) BuyItem(context.Context, *BuyItemRequest) (*BuyItemReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyItem not implemented")
}
func (UnimplementedShopServiceServer) ListOwnedItems(context.Context, *ListOwnedItemsRequest) (*ListOwnedItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOwnedItems not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}
func (UnimplementedShopServiceServer) testEmbeddedByValue()                     {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	// If the following call panics, it indicates UnimplementedShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_ListShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListShopItems(ctx, req.(*ListShopItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetDailyDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetDailyDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetDailyDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetDailyDeal(ctx, req.(*GetDailyDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_BuyItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).BuyItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_BuyItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).BuyItem(ctx, req.(*BuyItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListOwnedItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOwnedItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListOwnedItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListOwnedItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListOwnedItems(ctx, req.(*ListOwnedItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.shop.v1.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListShopItems",
			Handler:    _ShopService_ListShopItems_Handler,
		},
		{
			MethodName: "GetDailyDeal",
			Handler:    _ShopService_GetDailyDeal_Handler,
		},
		{
			MethodName: "BuyItem",
			Handler:    _ShopService_BuyItem_Handler,
		},
		{
			MethodName: "ListOwnedItems",
			Handler:    _ShopService_ListOwnedItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/v1/shop.proto",
}
