// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: shop/v1/shop.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShopServiceBuyItem = "/api.shop.v1.ShopService/BuyItem"
const OperationShopServiceGetDailyDeal = "/api.shop.v1.ShopService/GetDailyDeal"
const OperationShopServiceListOwnedItems = "/api.shop.v1.ShopService/ListOwnedItems"
const OperationShopServiceListShopItems = "/api.shop.v1.ShopService/ListShopItems"

type ShopServiceHTTPServer interface {
	// BuyItem BuyItem purchases an item with gold or gems.
	BuyItem(context.Context, *BuyItemRequest) (*BuyItemReply, error)
	// GetDailyDeal GetDailyDeal returns the current rotating discounted item.
	GetDailyDeal(context.Context, *GetDailyDealRequest) (*GetDailyDealReply, error)
	// ListOwnedItems ListOwnedItems lists items the current user owns.
	ListOwnedItems(context.Context, *ListOwnedItemsRequest) (*ListOwnedItemsReply, error)
	// ListShopItems ListShopItems lists all purchasable shop items.
	ListShopItems(context.Context, *ListShopItemsRequest) (*ListShopItemsReply, error)
}

func RegisterShopServiceHTTPServer(s *http.Server, srv ShopServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/shop/items", _ShopService_ListShopItems0_HTTP_Handler(srv))
	r.GET("/api/v1/shop/daily-deal", _ShopService_GetDailyDeal0_HTTP_Handler(srv))
	r.POST("/api/v1/shop/items/{item_id}/buy", _ShopService_BuyItem0_HTTP_Handler(srv))
	r.GET("/api/v1/shop/owned", _ShopService_ListOwnedItems0_HTTP_Handler(srv))
}

func _ShopService_ListShopItems0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShopItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListShopItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShopItems(ctx, req.(*ListShopItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShopItemsReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_GetDailyDeal0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDailyDealRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceGetDailyDeal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDailyDeal(ctx, req.(*GetDailyDealRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDailyDealReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_BuyItem0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BuyItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceBuyItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BuyItem(ctx, req.(*BuyItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BuyItemReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_ListOwnedItems0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOwnedItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListOwnedItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOwnedItems(ctx, req.(*ListOwnedItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOwnedItemsReply)
		return ctx.Result(200, reply)
	}
}

type ShopServiceHTTPClient interface {
	// BuyItem BuyItem purchases an item with gold or gems.
	BuyItem(ctx context.Context, req *BuyItemRequest, opts ...http.CallOption) (rsp *BuyItemReply, err error)
	// GetDailyDeal GetDailyDeal returns the current rotating discounted item.
	GetDailyDeal(ctx context.Context, req *GetDailyDealRequest, opts ...http.CallOption) (rsp *GetDailyDealReply, err error)
	// ListOwnedItems ListOwnedItems lists items the current user owns.
	ListOwnedItems(ctx context.Context, req *ListOwnedItemsRequest, opts ...http.CallOption) (rsp *ListOwnedItemsReply, err error)
	// ListShopItems ListShopItems lists all purchasable shop items.
	ListShopItems(ctx context.Context, req *ListShopItemsRequest, opts ...http.CallOption) (rsp *ListShopItemsReply, err error)
}

type ShopServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopServiceHTTPClient(client *http.Client) ShopServiceHTTPClient {
	return &ShopServiceHTTPClientImpl{client}
}

// BuyItem BuyItem purchases an item with gold or gems.
func (c *ShopServiceHTTPClientImpl) BuyItem(ctx context.Context, in *BuyItemRequest, opts ...http.CallOption) (*BuyItemReply, error) {
	var out BuyItemReply
	pattern := "/api/v1/shop/items/{item_id}/buy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceBuyItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDailyDeal GetDailyDeal returns the current rotating discounted item.
func (c *ShopServiceHTTPClientImpl) GetDailyDeal(ctx context.Context, in *GetDailyDealRequest, opts ...http.CallOption) (*GetDailyDealReply, error) {
	var out GetDailyDealReply
	pattern := "/api/v1/shop/daily-deal"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceGetDailyDeal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListOwnedItems ListOwnedItems lists items the current user owns.
func (c *ShopServiceHTTPClientImpl) ListOwnedItems(ctx context.Context, in *ListOwnedItemsRequest, opts ...http.CallOption) (*ListOwnedItemsReply, error) {
	var out ListOwnedItemsReply
	pattern := "/api/v1/shop/owned"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListOwnedItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListShopItems ListShopItems lists all purchasable shop items.
func (c *ShopServiceHTTPClientImpl) ListShopItems(ctx context.Context, in *ListShopItemsRequest, opts ...http.CallOption) (*ListShopItemsReply, error) {
	var out ListShopItemsReply
	pattern := "/api/v1/shop/items"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListShopItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
